In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd

%load_ext autoreload
%autoreload 2


pd.set_option('display.max_columns', None)

# Dataset 1: Alternative Fuel Vehicles

In [3]:
# Carga el archivo CSV en un DataFrame
df1 = pd.read_csv("datasets/datasets_originales/Alternative Fuel Vehicles US.csv")

In [4]:
df1

,Category,Model,Model Year,Manufacturer,Fuel,All-Electric Range,PHEV Total Range,Alternative Fuel Economy City,Alternative Fuel Economy Highway,Alternative Fuel Economy Combined,Conventional Fuel Economy City,Conventional Fuel Economy Highway,Conventional Fuel Economy Combined,Transmission Type,Transmission Make,Engine Type,Engine Size,Engine Cylinder Count,Number of Passengers,Heavy-Duty Power System,Notes,Drivetrain
0,Sedan/Wagon,NSX,2022.0,Acura,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,21.0,22.0,21.0,Auto,NaN,SI,3.5L,6.0,NaN,NaN,NaN,AWD
1,Sedan/Wagon,A3,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,29.0,38.0,32.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,FWD
2,Sedan/Wagon,A3 quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,28.0,36.0,31.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD
3,Sedan/Wagon,A4 allroad quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,24.0,30.0,26.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD
4,Sedan/Wagon,A4 quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,26.0,34.0,29.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,Street Sweeper,HSP,NaN,TYMCO,CNG - Compressed Natural Gas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cummins Westport L9N 8.9L Near Zero,NaN,NaN
878,Step Van,(various models),NaN,Utilimaster,Electric,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Automatic,NaN,NaN,NaN,NaN,NaN,NaN,According to manufacturer: Various platforms a...,NaN
879,Transit Bus,CX45E,NaN,Van Hool,Electric,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Up to 56,Siemens ELFA2 Electric Drive System 360kW,According to manufacturer: 676 kWh battery sto...,NaN
880,Tractor,VNR Electric - Class 8,NaN,Volvo,Electric,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"According to manufacturer: 340kW; 455hp; 4,051...",NaN
881,Step Van,C-Series,NaN,Workhorse,Electric,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Automatic,NaN,NaN,NaN,NaN,NaN,Workhorse Dual Axial Flux Interior Permanent M...,According to manufacturer: Up to 105 kWh batte...,NaN

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 22 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Category                            882 non-null    object
 1   Model                               882 non-null    object
 2   Model Year                          594 non-null    float64
 3   Manufacturer                        882 non-null    object
 4   Fuel                                882 non-null    object
 5   All-Electric Range                  222 non-null    float64
 6   PHEV Total Range                    43 non-null     float64
 7   Alternative Fuel Economy City       169 non-null    float64
 8   Alternative Fuel Economy Highway    169 non-null    float64
 9   Alternative Fuel Economy Combined   262 non-null    float64
 10  Conventional Fuel Economy City      444 non-null    float64
 11  Conventional Fuel Economy Highway   444 non-null    float64
 12  Conventional Fuel Economy Combined  444 non-null    float64
 13  Transmission Type                   640 non-null    object
 14  Transmission Make                   125 non-null    object
 15  Engine Type                         589 non-null    object
 16  Engine Size                         589 non-null    object
 17  Engine Cylinder Count               449 non-null    float64
 18  Number of Passengers                121 non-null    object
 19  Heavy-Duty Power System             245 non-null    object
 20  Notes                               179 non-null    object
 21  Drivetrain                          329 non-null    object
dtypes: float64(10), object(12)
memory usage: 151.7+ KB

In [6]:
df1.describe()

,Model Year,All-Electric Range,PHEV Total Range,Alternative Fuel Economy City,Alternative Fuel Economy Highway,Alternative Fuel Economy Combined,Conventional Fuel Economy City,Conventional Fuel Economy Highway,Conventional Fuel Economy Combined,Engine Cylinder Count
count,594.000000,222.000000,43.000000,169.000000,169.000000,262.000000,444.000000,444.000000,444.000000,449.000000
mean,2021.538721,165.927928,450.465116,84.585799,77.591716,75.992366,25.900901,30.085586,27.261261,5.452116
std,0.498919,132.992955,93.042578,39.430696,32.735123,32.303279,10.860665,12.815653,9.803912,1.396121
min,2021.000000,8.000000,290.000000,10.000000,12.000000,11.000000,13.000000,16.000000,15.000000,3.000000
25%,2021.000000,23.000000,380.000000,71.000000,66.000000,56.000000,19.000000,24.000000,21.000000,4.000000
50%,2022.000000,203.000000,460.000000,94.000000,85.000000,76.000000,22.000000,28.000000,24.000000,6.000000
75%,2022.000000,260.000000,520.000000,115.000000,99.000000,101.000000,28.000000,33.000000,30.000000,6.000000
max,2022.000000,520.000000,640.000000,150.000000,133.000000,142.000000,59.000000,231.000000,59.000000,8.000000

In [7]:
df1.isnull().sum()

Category                                0
Model                                   0
Model Year                            288
Manufacturer                            0
Fuel                                    0
All-Electric Range                    660
PHEV Total Range                      839
Alternative Fuel Economy City         713
Alternative Fuel Economy Highway      713
Alternative Fuel Economy Combined     620
Conventional Fuel Economy City        438
Conventional Fuel Economy Highway     438
Conventional Fuel Economy Combined    438
Transmission Type                     242
Transmission Make                     757
Engine Type                           293
Engine Size                           293
Engine Cylinder Count                 433
Number of Passengers                  761
Heavy-Duty Power System               637
Notes                                 703
Drivetrain                            553
dtype: int64

In [8]:
df1.head()

,Category,Model,Model Year,Manufacturer,Fuel,All-Electric Range,PHEV Total Range,Alternative Fuel Economy City,Alternative Fuel Economy Highway,Alternative Fuel Economy Combined,Conventional Fuel Economy City,Conventional Fuel Economy Highway,Conventional Fuel Economy Combined,Transmission Type,Transmission Make,Engine Type,Engine Size,Engine Cylinder Count,Number of Passengers,Heavy-Duty Power System,Notes,Drivetrain
0,Sedan/Wagon,NSX,2022.0,Acura,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,21.0,22.0,21.0,Auto,NaN,SI,3.5L,6.0,NaN,NaN,NaN,AWD
1,Sedan/Wagon,A3,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,29.0,38.0,32.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,FWD
2,Sedan/Wagon,A3 quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,28.0,36.0,31.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD
3,Sedan/Wagon,A4 allroad quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,24.0,30.0,26.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD
4,Sedan/Wagon,A4 quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,NaN,NaN,NaN,26.0,34.0,29.0,Auto,NaN,SI,2.0L,4.0,NaN,NaN,NaN,AWD

### Diccionario:

1. **Category:** Tipo de vehículo, por ejemplo, Sedán o Vagón.
2. **Model:** Modelo específico del vehículo.
3. **Model Year:** Año del modelo del vehículo.
4. **Manufacturer:** Fabricante del vehículo.
5. **Fuel:** Tipo de combustible utilizado por el vehículo.
6. **All-Electric Range:** Rango completamente eléctrico del vehículo (en millas o km).
7. **PHEV Total Range:** Rango total para vehículos híbridos enchufables (en millas o km).
8. **Alternative Fuel Economy City:** Economía de combustible en ciudad para vehículos de combustible alternativo.
9. **Alternative Fuel Economy Highway:** Economía de combustible en carretera para vehículos de combustible alternativo.
10. **Alternative Fuel Economy Combined:** Economía de combustible combinada para vehículos de combustible alternativo.
11. **Conventional Fuel Economy City:** Economía de combustible en ciudad para vehículos convencionales.
12. **Conventional Fuel Economy Highway:** Economía de combustible en carretera para vehículos convencionales.
13. **Conventional Fuel Economy Combined:** Economía de combustible combinada para vehículos convencionales.
14. **Transmission Type:** Tipo de transmisión del vehículo (por ejemplo, automático).
15. **Transmission Make:** Fabricante de la transmisión.
16. **Engine Type:** Tipo de motor del vehículo.
17. **Engine Size:** Tamaño del motor del vehículo.
18. **Engine Cylinder Count:** Número de cilindros en el motor.
19. **Number of Passengers:** Número de pasajeros que puede acomodar el vehículo.
20. **Heavy-Duty Power System:** Sistema de energía pesado para vehículos de trabajo pesado.
21. **Notes:** Notas adicionales o información sobre el vehículo.
22. **Drivetrain:** Configuración de la transmisión y tracción del vehículo (por ejemplo, AWD para tracción en todas las ruedas).

In [9]:
# Verificar filas duplicadas en df1
duplicates = df1.duplicated()

# Contar el número total de filas duplicadas
total_duplicates = duplicates.sum()

# Mostrar las filas duplicadas si es necesario
duplicated_rows = df1[duplicates]

# Imprimir resultados
print(f"Número total de filas duplicadas: {total_duplicates}")

Número total de filas duplicadas: 1

Al profundizar en el análisis de los datos, se destaca la presencia de columnas con un alto número de valores faltantes, como PHEV Range, Transmission Make, Heavy-duty Power System, Notes y Number of Passengers. Estas columnas podrían no ser críticas para nuestro análisis, ya que la falta de información podría afectar la interpretación y utilidad de los resultados. La ausencia de datos en estas categorías podría deberse a varias razones, como la falta de disponibilidad de información o la naturaleza específica de ciertos vehículos que no requieren estas especificaciones.

En el caso de Engine Size y Engine Cylinder Count, se podría argumentar que ambas proporcionan información similar sobre las características del motor. Dado que Engine Size se considera una medida más integral del motor, podría ser preferible mantener esta variable y descartar Engine Cylinder Count para simplificar el conjunto de datos y reducir la complejidad sin perder información esencial.

Asimismo, es importante considerar que el análisis de datos se centra en aspectos relevantes para la producción de CO2, y la relación entre Engine Size y las emisiones de CO2 podría ser un área clave de exploración. Esto destaca la necesidad de realizar elecciones estratégicas en cuanto a las variables a incluir en el análisis para obtener resultados más significativos y aplicables a la problemática abordada.

In [10]:
df1_filtered = df1[['Category', 'Model', 'Model Year', 'Manufacturer', 'Fuel', 'All-Electric Range','Alternative Fuel Economy Combined','Conventional Fuel Economy Combined', 'Transmission Type','Engine Size']]

In [11]:
df1_filtered.head(3)

,Category,Model,Model Year,Manufacturer,Fuel,All-Electric Range,Alternative Fuel Economy Combined,Conventional Fuel Economy Combined,Transmission Type,Engine Size
0,Sedan/Wagon,NSX,2022.0,Acura,Hybrid Electric,NaN,NaN,21.0,Auto,3.5L
1,Sedan/Wagon,A3,2022.0,Audi,Hybrid Electric,NaN,NaN,32.0,Auto,2.0L
2,Sedan/Wagon,A3 quattro,2022.0,Audi,Hybrid Electric,NaN,NaN,31.0,Auto,2.0L

In [12]:
df1_filtered['Category'].unique()

array(['Sedan/Wagon', 'SUV', 'Pickup', 'Van', 'Passenger Van/Shuttle Bus',
       'Street Sweeper', 'Refuse', 'Vocational/Cab Chassis', 'Tractor',
       'School Bus', 'Transit Bus', 'Step Van',
       'TractorVocational/Cab Chassis', 'Vocational/Cab ChassisVan',
       'Vocational/Cab ChassisTractor'], dtype=object)

In [13]:
df1_filtered['Model'].unique()

array(['NSX', 'A3 ', 'A3 quattro', 'A4 allroad quattro', 'A4 quattro',
       'A4 S line quattro', 'A5 Cabriolet quattro', 'A5 Coupe quattro',
       'A5 Sportback quattro', 'A5 Sportback S line quattro',
       'A6 Allroad quattro', 'A6 quattro', 'A7 quattro',
       'A7 TFSI e quattro', 'A8L quattro', 'e-tron GT', 'e-tron quattro',
       'e-tron S (20" wheels)', 'e-tron S (21" or 22" wheels)',
       'e-tron Sportback quattro', 'e-tron S Sportback (20" wheels)',
       'e-tron S Sportback (21" or 22" wheels)', 'Q4 e-tron quattro',
       'Q4 e-tron Sportback quattro', 'Q5 quattro', 'Q5 S line quattro',
       'Q5 Sportback S line quattro', 'Q5 TFSI e quattro', 'Q7 quattro',
       'Q8 quattro', 'RS 6 Avant', 'RS7', 'RS e-tron GT', 'RS Q8', 'S6',
       'S7', 'S8', 'Flying Spur Hybrid', '330e Sedan', '330e xDrive',
       '530e Sedan', '530e xDrive Sedan', '540i Sedan',
       '540i xDrive Sedan', '745e xDrive',
       'i4 eDrive40 Gran Coupe (18" Wheels) ',
       'i4 eDrive40 Gran Coupe (19" Wheels) ',
       'i4 M50 Gran Coupe (19" Wheels) ',
       'i4 M50 Gran Coupe (20" Wheels) ', 'iX xDrive50 (20" Wheels) ',
       'iX xDrive50 (21" Wheels) ', 'iX xDrive50 (22" Wheels) ',
       'M340i Sedan', 'M340i xDrive Sedan', 'M440i Convertible',
       'M440i Coupe', 'M440i xDrive Convertible', 'M440i xDrive Coupe',
       'M440i xDrive Gran Coupe', 'X3 M40i', 'X4 M40i', 'X5 sDrive40i',
       'X5 xDrive40i', 'X5 xDrive45e', 'X6 xDrive40i', 'X7 xDrive40i',
       'Escalade 2WD', 'Escalade 4WD', 'Bolt EUV', 'Bolt EV',
       'Colorado 2WD', 'Colorado 4WD', 'Colorado ZR2 4WD',
       'Silverado 2WD', 'Silverado 4WD',
       'Silverado 4WD - Mud Terrain Tires', 'Suburban 2WD',
       'Suburban 4WD', 'Tahoe 2WD', 'Tahoe 4WD', 'Pacifica Hybrid',
       'SF90 Spyder', 'SF90 Stradale ', 'Escape AWD HEV',
       'Escape FWD HEV', 'Escape FWD PHEV', 'Explorer AWD FFV',
       'Explorer HEV AWD', 'Explorer HEV RWD', 'Explorer Platinum HEV ',
       'F-150 2WD FFV', 'F-150 2WD FFV - Without Start/Stop',
       'F-150 2WD FFV - With Start/Stop', 'F-150 4WD FFV',
       'F-150 4WD FFV - Without Start/Stop',
       'F-150 4WD FFV - With Start/Stop', 'F150 Lightning 4WD',
       'F150 Lightning 4WD Extended Range', 'F150 Lightning Platinum 4WD',
       'F150 Pickup 2WD HEV', 'F150 Pickup 4WD HEV',
       'Maverick Pickup HEV', 'Mustang Mach-E AWD',
       'Mustang Mach-E AWD California Route 1',
       'Mustang Mach-E AWD Extended', 'Mustang Mach-E GT AWD',
       'Mustang Mach-E GT Performance', 'Mustang Mach-E RWD',
       'Mustang Mach-E RWD California Route 1',
       'Mustang Mach-E RWD Extended', 'Transit Connect Van FFV',
       'Transit Connect Wagon LWB FFV',
       'Transit T150 Passenger Van 2WD FFV',
       'Transit T150 Passenger Van 4WD FFV', 'Canyon 2WD', 'Canyon 4WD',
       'Sierra 2WD', 'Sierra 4WD', 'Sierra 4WD - Mud Terrain Tires',
       'Yukon 2WD', 'Yukon 4WD', 'Yukon XL 2WD', 'Yukon XL 4WD', 'Accord',
       'Accord Sport/Touring', 'CR-V AWD', 'Insight', 'Insight Touring',
       'Elantra Hybrid', 'Elantra Hybrid Blue', 'Ioniq',
       'Ioniq 5 AWD (Long Range)', 'Ioniq 5 RWD',
       'Ioniq 5 RWD (Long Range)', 'Ioniq Blue', 'Ioniq Plug-in Hybrid',
       'Kona Electric', 'Nexo', 'Nexo Blue', 'Santa Fe Hybrid',
       'Santa Fe Hybrid Blue', 'Santa Fe Plug-in Hybrid', 'Sonata Hybrid',
       'Sonata Hybrid Blue', 'Tucson Hybrid', 'Tucson Hybrid Blue',
       'Tucson Plug-in Hybrid', 'E-PACE MHEV', 'F-PACE P340 MHEV',
       'F-PACE P400 MHEV', 'Grand Cherokee 4xe', 'Wagoneer 4x2',
       'Wagoneer 4x4', 'Wrangler 2dr 4x4', 'Wrangler 4dr 4x4',
       'Wrangler 4dr 4xe', 'EV6 AWD (Long Range) ', 'EV6 RWD',
       'EV6 RWD (Long Range) ', 'Niro', 'Niro Electric', 'Niro FE',
       'Niro Plug-in Hybrid', 'Niro Touring', 'Sorento Hybrid AWD',
       'Sorento Hybrid FWD', 'Sorento Plug-in Hybrid',
       'Defender 110 MHEV', 'Defender 90 MHEV', 'Discovery MHEV',
       'New Range Rover P360 LWB MHEV', 'New Range Rover P360 MHEV',
       'New Range Rover P400 LWB MHEV', 'New Range Rover P400 MHEV',
       'Range Rover Evoque MHEV', 'Range Rover P360 MHEV',
       'Range Rover P400 MHEV', 'Range Rover Sport P360 MHEV',
       'Range Rover Sport P400 MHEV', 'Range Rover Sport PHEV',
       'Range Rover Velar P340 MHEV', 'Range Rover Velar P400 MHEV',
       'ES 300h', 'LC 500h', 'LS 500h AWD', 'NX 350h AWD', 'NX 450+ AWD',
       'RX 450h AWD', 'RX 450h L AWD', 'UX 250h', 'UX 250h AWD',
       'Aviator AWD PHEV', 'Corsair AWD PHEV',
       'Air Dream P AWD w/19" wheels', 'Air Dream P AWD w/21" wheels',
       'Air Dream R AWD w/19" wheels', 'Air Dream R AWD w/21" wheels',
       'Air G Touring AWD w/19" wheels', 'Air G Touring AWD w/21" wheels',
       'MX-30', 'AMG E53 4MATIC+', 'AMG E53 4MATIC+ (Convertible)',
       'AMG E53 4MATIC+ (Coupe)', 'AMG GLE 53 4MATIC+',
       'AMG GLE 53 4MATIC+ (Coupe)', 'AMG GLE 63 4MATIC+',
       'AMG GLE 63 S 4MATIC+', 'AMG GLE 63 S 4MATIC+ (coupe)',
       'AMG GT 43 4MATIC+', 'AMG GT 53 4MATIC+', 'C 300', 'C 300 4MATIC',
       'CLS 450 4MATIC', 'E 450 4MATIC',
       'E 450 4MATIC All-Terrain (wagon)', 'E 450 4MATIC (Convertible)',
       'E 450 4MATIC (Coupe)', 'E 450 (Convertible)', 'E 450 (Coupe)',
       'EQS450+', 'EQS 580 4MATIC', 'GLE 450 4MATIC', 'GLE 580 4MATIC',
       'GLS 450 4MATIC', 'GLS 580 4MATIC', 'GLS 600 4MATIC Maybach',
       'S 500 4MATIC', 'S 580 4MATIC', 'S 580 4MATIC Maybach',
       'Cooper SE Countryman ALL4', 'Cooper SE Hardtop 2 door',
       'Outlander PHEV', 'Leaf (40 kWh battery pack)',
       'Leaf (62 kWh battery pack)', 'Leaf SV/SL (62 kWh battery pack)',
       'Polestar 2 (Dual Motor)', 'Polestar 2 (Single Motor)',
       'Cayenne/Coupe/Platinum e-Hybrid',
       'Cayenne Turbo S/Coupe e-Hybrid ', 'Panamera 4 E-Hybrid Executive',
       'Panamera 4S E-Hybrid Executive',
       'Panamera Turbo S E-Hybrid Executive/ST', 'Taycan 4 Cross Turismo',
       'Taycan 4S Cross Turismo', 'Taycan 4S Perf Battery',
       'Taycan 4S Perf Battery Plus', 'Taycan Perf Battery',
       'Taycan Perf Battery Plus', 'Taycan Turbo',
       'Taycan Turbo Cross Turismo', 'Taycan Turbo S',
       'Taycan Turbo S Cross Turismo', '1500 4X2', '1500 4X4',
       '1500 HFE 4X2', 'R1S', 'R1T', 'Model 3 (Long Range) AWD',
       'Model 3 Performance AWD', 'Model 3 RWD', 'Model S ',
       'Model S Plaid (19" Wheels)', 'Model S Plaid (21" Wheels)',
       'Model X AWD', 'Model X Plaid (20" Wheels)',
       'Model X Plaid (22" Wheels)', 'Model Y AWD',
       'Model Y (Long Range) AWD', 'Model Y Performance AWD',
       'Model Y RWD', 'Avalon Hybrid ', 'Avalon Hybrid XLE',
       'Camry Hybrid LE', 'Camry Hybrid SE/XLE/XSE', 'Corolla Hybrid',
       'Highlander Hybrid', 'Highlander Hybrid AWD',
       'Highlander Hybrid AWD LTD/PLAT', 'Mirai LE', 'Mirai Limited',
       'Mirai XLE', 'Prius', 'Prius AWD', 'Prius Eco', 'Prius Prime',
       'RAV4 Hybrid AWD', 'RAV4 Prime AWD', 'Sienna AWD', 'TUNDRA 2WD',
       'TUNDRA 4WD', 'TUNDRA 4WD PRO', 'Venza AWD', 'ID.4 AWD Pro',
       'ID.4 AWD Pro S', 'ID.4 Pro', 'ID.4 Pro S', 'C40 Recharge Twin',
       'S60 T8 AWD Recharge', 'S60 T8 AWD Recharge ext. Range',
       'S90 T8 AWD Recharge', 'S90 T8 AWD Recharge ext. Range',
       'V60 T8 AWD Recharge', 'V60 T8 AWD Recharge ext. Range',
       'XC40 Recharge Twin', 'XC60 T8 AWD Recharge',
       'XC60 T8 AWD Recharge ext. Range', 'XC90 T8 AWD Recharge',
       'XC90 T8 AWD Recharge ext. Range', 'A5 quattro', 'A6 Allroad',
       'A8L', 'e-tron', 'e-tron Sportback', 'Q5', 'Q5 Sportback', 'Q7',
       'Q8', 'Bentayga', '330e', '530e', '530e xDrive', '540i',
       '540i xDrive', 'i3', 'i3s', 'i3s with Range Extender',
       'i3 with Range Extender', 'M340i', 'M340i xDrive', 'X3 xDrive30e',
       'X5 sDrive40i 2WD', 'X5 sDrive40i 4WD', 'X6 sDrive40i 2WD',
       'X6 sDrive40i 4WD', 'X7 sDrive40i 4WD', 'SF90 Stradale Coupe',
       'F-150 2WD', 'F-150 4WD', 'Super Duty F-250',
       'Super Duty F-250 2WD/4WD', 'Transit Connect Van/Wagon',
       'Sierra 4WD AT4', 'Clarity', 'Clarity PHEV', 'Ioniq Electric',
       'I-PACE EV400', 'K27', 'GS-6 (21" wheels)',
       'Revero GT (21" wheels)', 'Sorento Hybrid', 'Range Rover ',
       'Range Rover MHEV', 'Range Rover PHEV', 'Range Rover Sport',
       'Range Rover Sport MHEV', 'LS 500h', 'NX 300h AWD',
       'AMG CLS 53 4MATIC+', 'AMG GLE 53 4MATIC+ Coupe',
       'AMG GLE 63 S 4MATIC+ Coupe', 'AMG GLS 63 4MATIC+', 'CLS 450',
       'Polestar 2', 'Polestar I', 'Cayenne e-Hybrid',
       'Cayenne e-Hybrid Coupe', 'Cayenne Turbo S e-Hybrid',
       'Cayenne Turbo S e-Hybrid Coupe', 'Panamera 4 E-Hybrid',
       'Panamera 4 E-Hybrid ST', 'Panamera 4S E-Hybrid',
       'Panamera 4S E-Hybrid ST', 'Panamera Turbo S E-Hybrid',
       'Panamera Turbo S E-Hybrid Executive',
       'Panamera Turbo S E-Hybrid ST', '1500 2WD', '1500 4WD',
       'Crosstrek Hybrid AWD', 'Model 3 Long Range AWD',
       'Model 3 Standard Range Plus RWD', 'Model S Long Range',
       'Model S Performance (19" Wheels)', 'Model X Long Range Plus',
       'Model X Performance (20" Wheels)', 'Model Y Long Range AWD',
       'Model Y Standard Range RWD', 'Avalon Hybrid', 'Sienna',
       'ID.4 1st', 'ID.4 Pro S AWD ', 'S60 AWD', 'S90 AWD', 'V60 AWD',
       'XC40 Recharge', 'XC60 AWD', 'XC90 AWD', 'ACMD-Xpert',
       'ACTT Terminal Tractor', 'ACX-Xpeditor  - Class 8',
       'ACX-Xpeditor ', 'DC-64 - Class 8', 'DC-64R - Class 8', 'LET2',
       'LET2 Crew Cab', 'LNT', 'All American Activity',
       'All American Rear Engine - Class 7', 'All American RE Electric',
       'All American RE Electric Activity',
       'Micro Bird Activity G5 Electric', 'Micro Bird G5 - Class 3',
       'Micro Bird G5 Activity', 'Micro Bird G5 Electric',
       'Vision - Class 7', 'Vision Activity', 'Vision Electric',
       'Vision Electric Activity', '6F', '6R', '8R', '8TT Day Cab',
       '8Y Terminal Tractor', "C10M (45')", "C10MS (45' double deck)",
       "C6M (23')", "C8M (35')", "C8MS (35' double deck)", "C9M (40')",
       "K11M (60')", "K7M (30')", "K7M ER (30')", "K8M (35')",
       "K9M (40')", "K9MD (40')", '3500/4500 Low Cab Forward',
       '4500 HD, 4500 XD, 5500 HD, 5500 XD Low Cab Forward',
       '6500 XD Low Cab Forward', 'Express 2500/3500',
       'Express 3500/4500 Cutaway', 'Silverado 3500 HD Cab Chassis',
       'Sliverado 2500/3500 HD', 'e.COBUS 2700', 'e.COBUS 2700S',
       'e.COBUS 3000', 'Type A Electric School Bus (DE516)',
       'Type A Electric School Bus (DE516WF)', 'Broom Bear',
       'Broom Bear CNG Hybrid', 'Broom Bear Plug-In Hybrid', 'Crosswind1',
       'Pelican', "AXESS 32' low floor", "AXESS 35' low floor",
       "AXESS 40' low floor", "Axess-BEB 32' low floor",
       "Axess-BEB 35' low floor", "Axess-BEB 40' low floor",
       "AXESS-FC 40' low floor", "E-Z RIDER II 30'", "E-Z RIDER II 32'",
       "E-Z RIDER II 35'", "XHF 29'", "XHF 33'", "XHF 35'", "XHF 40'",
       'E350, E450 Cutaway', 'E350, E450 Stripped Chassis',
       'E-450 Box Truck', 'E450 Cutaway', 'E-450 School Bus',
       'E-450 Shuttle', 'E-450 Step Van', 'E450 Stripped Chassis',
       'E-450 Work Truck', 'E-Transit Cargo Van',
       'E-Transit Cutaway/Chassis Cab', 'F-550 Bus', 'F-59 School Bus',
       'F-59 Shuttle Bus', 'F-59 Step Van', 'F-59 Stripped Chassis',
       'F-650 Box Truck', 'Medium Duty Chassis Cab F650, F750',
       'Super Duty Chassis Cab F350',
       'Super Duty Chassis Cab F350, F450, F550',
       'Super Duty F250, F350, F450', 'Transit 250/350 Cargo Van',
       'Transit 250/350 Passenger Van', 'Transit CC-CA 250, 350',
       'Transit Cutaway/Chassis Cab', '114SD NG - Class 8',
       'Cascadia Natural Gas', 'M2 112 NG', 'MT-45 G Chassis - Class 4',
       'MT-50e', 'MT-55 G Chassis', 'S2G Truck - Class 6', 'eCanter',
       'BRT, BRT Plus, Commuter', 'Low Floor, Low Floor Plus',
       'Low Floor Plus', 'Trolley', 'M3EV - Class 7', 'M4EV - Class 7',
       'M4 Hybrid', 'M4/M4HSD CNG', 'M4ZE/M4HSDZE - Class 7', 'Zevo 600',
       'Savana 2500/3500', 'Savana 3500/4500 Cutaway',
       'Sierra 2500/3500 HD', 'Sierra 3500 HD Cab Chassis', 'G1, G2',
       'G3, G4', 'AV Star', 'BEAST', 'EV250', 'EV350', 'EV550', 'EV Star',
       'EV Star+', 'EV Star Cargo', 'EV Star Cargo+', 'EV Star CC',
       'Front Loader: Half/Pack (including Automated), Half/Pack Freedom, Half/Pack Sierra, Half/Pack Low Rider (including Automated)',
       'Rear Loader: PowerTrak, PowerTrak Commercial, DuraPack 4060 and 5000, PT 1000, Under CDL Mini Rear Loader',
       'Side Loader: Command-SST, DuraPack Python and Rapid Rail, Liberty and MultiPack Automated',
       'L6 Conventional', 'L7 Conventional', 'XL7 Conventional',
       'XL8 Conventional', 'Carriage ', 'Commuter', 'Mainstreet',
       'Streetcar', 'Urban', 'View', 'Villager', 'CE Series',
       'Electric CE Series', 'eMV', 'FTR, FVR',
       'NPR-HD, NPR-XD, NQR, NRR', 'Ottawa T2E+', 'K270/K370',
       'T180/T280', 'T680', 'T680E', 'T880', 'LION6', 'LION8 - Class 8',
       'LION8 Refuse ASL and REL - Class 8', 'LION8T - Class 8', 'LIONA',
       'LIONC', 'LIOND', 'LIONM', 'Anthem - Class 8', 'LR',
       'TerraPro Cab Over', 'D4000 Commuter Coach',
       'D4000 Hybrid Commuter Coach - Class 8', 'D4500 Commuter Coach',
       'D4500 Hybrid Commuter Coach - Class 8',
       'D45 CRT LE CHARGE - Class 8', 'J4500e CHARGE - Class 8',
       'Front Loaders: Meridian, Atlantic, Contendor - Class 8',
       'Rear Loader: Standard, Heavy Duty, Extra Compaction,Tag Axle, Split Body, M2 - Class 8',
       'Side Loader: AutoReach, Manual/Automated, Zero Radius - Class 8',
       'Standard, Bridgemaster, Oshkosh S-Series - Class 8',
       '(various models)', "Xcelsior 35'", "Xcelsior 40'", "Xcelsior 60'",
       "Xcelsior CHARGE 35'", "Xcelsior CHARGE 40'",
       "Xcelsior CHARGE 60'", "Xcelsior CHARGE H2 40'",
       "Xcelsior CHARGE H2 60'", 'Osprey II sweeper', 'Raptor II sweeper',
       'LFS Artic HEV - Class 8', 'LFS CNG - Class 8', 'LFSe', 'LFSe+',
       'LFS HEV - Class 8', 'E1 Cutaway Chassis', 'S1 LF Low Floor',
       'T Series terminal', '220EV - Class 6', '220EV - Class 7', '520',
       '520EV - Class 8', '535 - Class 5', '536 - Class 6',
       '537 - Class 7', '548 - Class 8', '567 - Class 8', '579',
       '579EV - Class 8', 'ZX5 35-Foot Bus - Class 8',
       'ZX5+ 35-Foot Bus - Class 8', 'ZX5 40-Foot Bus - Class 8',
       'ZX5+ 40-Foot Bus - Class 8', 'ZX5MAX 40-Foot Bus - Class 8',
       '2500/3500 HD', '3500/4500/5500', 'A7 Tornado sweeper - Class 6',
       'A7 Zephyr sweeper - Class 6', 'M6 Avalanche', 'Allstar 22',
       'E-Quest', 'E-Quest XL', 'Minotour - Class 4',
       'Minotour Activity - Class 4', 'Saf-T-Liner C2 Activity',
       'Saf-T-Liner C2 Jouley', 'Saf-T-Liner HDX - Class 8',
       'Saf-T-Liner HDX Activity - Class 8', 'Transit-Liner C2',
       'Transit-Liner HDX', 'Pro Spotter', 'Ford - Odyssey',
       'Ford - Odyssey XL', 'Ford - Terra Transit', 'Ford - Van Terra',
       'Ford - VT3', '500x', '600', 'HSP', 'CX45E',
       'VNR Electric - Class 8', 'C-Series'], dtype=object)

In [14]:
df1_filtered['Model Year'].unique()

array([2022., 2021.,   nan])

In [15]:
df1_filtered['Model Year'] = df1_filtered['Model Year'].apply(lambda x: int(x) if pd.notnull(x) else int(0))

In [16]:
df1_filtered['Model Year'].unique()

array([2022, 2021,    0], dtype=int64)

In [17]:
df1_filtered['Manufacturer'].unique()

array(['Acura', 'Audi', 'Bentley Motors', 'BMW', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Ferrari', 'Ford', 'GMC', 'Honda', 'Hyundai', 'Jaguar',
       'Jeep', 'Kia', 'Land Rover', 'Lexus', 'Lincoln', 'Lucid USA, Inc.',
       'Mazda', 'Mercedes-Benz', 'Mini', 'Mitsubishi', 'Nissan',
       'Polestar Automotive USA', 'Porsche', 'Ram', 'Rivian ', 'Tesla',
       'Toyota', 'Volkswagen', 'Volvo', 'Kandi', 'Karma', 'Subaru',
       'Autocar', 'Battle Motors', 'Blue Bird', 'BYD', 'COBUS Industries',
       'Collins Bus Corp.', 'Elgin', 'ENC', 'Freightliner',
       'Freightliner Custom Chassis', 'FUSO', 'Gillig', 'Global',
       'GM BrightDrop', 'Greenkraft', 'GreenPower Motor Company',
       'Heil Environmental', 'Hino', 'Hometown Manufacturing', 'IC Bus',
       'International', 'Isuzu', 'Kalmar', 'Kenworth', 'Lion Electric',
       'Mack', 'MCI', 'McNeilus', 'Morgan-Olson', 'New Flyer', 'Nitehawk',
       'Nova Bus', 'Optimal-EV', 'Orange EV', 'Peterbilt', 'Proterra',
       'RAM', 'Schwarze Industries', 'Starcraft', 'Thomas Built', 'TICO',
       'Turtle Top', 'TYMCO', 'Utilimaster', 'Van Hool', 'Workhorse'],
      dtype=object)

In [18]:
df1_filtered['Transmission Type'].unique()

array(['Auto', nan, 'Automatic', 'Automatic|Manual', 'Manual|Automatic'],
      dtype=object)

In [19]:
df1_filtered['Transmission Type'] = df1_filtered['Transmission Type'].apply(lambda x : 'Automatic|Manual' if x == 'Manual|Automatic' else x)
df1_filtered['Transmission Type'] = df1_filtered['Transmission Type'].apply(lambda x: 'Manual' if pd.isnull(x) else x)
df1_filtered['Transmission Type'] = df1_filtered['Transmission Type'].replace({'Auto': 'Automatic'})

In [20]:
df1_filtered['Transmission Type'].unique()

array(['Automatic', 'Manual', 'Automatic|Manual'], dtype=object)

In [21]:
df1_filtered['Transmission Type'].value_counts()

Automatic           634
Manual              242
Automatic|Manual      6
Name: Transmission Type, dtype: int64

In [22]:
df1_filtered.shape

(882, 10)

Luego de una revisión exhaustiva de las variables en nuestro conjunto de datos df1, buscamos optimizar la manipulación y análisis de la información para obtener resultados más significativos. En este proceso, nos percatamos de que nuestro conjunto de datos original cuenta con 882 filas y 10 columnas. En este punto, es crucial contextualizar que nuestro objetivo principal es abordar la problemática de las emisiones de CO2 en vehículos alternativos y entender las variables que tienen un impacto significativo en este aspecto.

Para simplificar y mejorar la calidad de nuestros análisis, hemos identificado columnas con un alto porcentaje de valores faltantes y aquellas que podrían no contribuir de manera sustancial a nuestro objetivo específico. Con base en esta evaluación, decidimos descartar ciertas columnas, incluyendo PHEV Range, Transmission Make, Heavy-duty Power System, Notes y Number of Passengers, que presentaban un número considerable de valores faltantes y cuya utilidad podría ser limitada para nuestro enfoque.

Además, consideramos la relación entre Engine Size y Engine Cylinder Count, optando por conservar Engine Size debido a su naturaleza más integral y, posiblemente, más relevante en términos de consumo de combustible y emisiones de CO2. Este enfoque de refinamiento busca simplificar el conjunto de datos sin perder información crítica, permitiéndonos concentrarnos en variables clave que influyen en nuestro análisis.

Tras estas consideraciones, procedimos a eliminar posibles duplicados en nuestro conjunto de datos filtrado df1_filtered. Esta etapa de limpieza y optimización nos posiciona de manera más efectiva para realizar análisis más profundos y específicos, centrándonos en las variables seleccionadas y su impacto en las emisiones de CO2 en vehículos alternativos.

In [23]:
df1_filtered.drop_duplicates(subset=['Category', 'Model', 'Model Year', 'Manufacturer', 'Fuel'], inplace=True)

In [24]:
df1_filtered.shape

(867, 10)

In [25]:
df1_filtered.head(3)

,Category,Model,Model Year,Manufacturer,Fuel,All-Electric Range,Alternative Fuel Economy Combined,Conventional Fuel Economy Combined,Transmission Type,Engine Size
0,Sedan/Wagon,NSX,2022,Acura,Hybrid Electric,NaN,NaN,21.0,Automatic,3.5L
1,Sedan/Wagon,A3,2022,Audi,Hybrid Electric,NaN,NaN,32.0,Automatic,2.0L
2,Sedan/Wagon,A3 quattro,2022,Audi,Hybrid Electric,NaN,NaN,31.0,Automatic,2.0L

In [26]:
# Especifica el nombre del archivo
nombre_del_archivo = 'Alternative Fuel Vehicles US cleaned.csv'

# Guarda el DataFrame en el archivo CSV
df1_filtered.to_csv('datasets/datasets_cleaned/' + nombre_del_archivo, index=False, encoding='utf-8')
print(f'Se ha guardado el archivo {nombre_del_archivo}', 'en la carpeta datasets_cleaned')

Se ha guardado el archivo Alternative Fuel Vehicles US cleaned.csv en la carpeta datasets_cleaned

# Dataset 2: Electric and Alternative Fuel Charging Stations

In [27]:
df2 = pd.read_csv('datasets/datasets_originales/Electric and Alternative Fuel Charging Stations.csv')

In [28]:
df2.head(3)

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Plus4,Station Phone,Status Code,Expected Date,Groups With Access Code,Access Days Time,Cards Accepted,BD Blends,NG Fill Type Code,NG PSI,EV Level1 EVSE Num,EV Level2 EVSE Num,EV DC Fast Count,EV Other Info,EV Network,EV Network Web,Geocode Status,Latitude,Longitude,Date Last Confirmed,ID,Updated At,Owner Type Code,Federal Agency ID,Federal Agency Name,Open Date,Hydrogen Status Link,NG Vehicle Class,LPG Primary,E85 Blender Pump,EV Connector Types,Country,Intersection Directions (French),Access Days Time (French),BD Blends (French),Groups With Access Code (French),Hydrogen Is Retail,Access Code,Access Detail Code,Federal Agency Code,Facility Type,CNG Dispenser Num,CNG On-Site Renewable Source,CNG Total Compression Capacity,CNG Storage Capacity,LNG On-Site Renewable Source,E85 Other Ethanol Blends,EV Pricing,EV Pricing (French),LPG Nozzle Types,Hydrogen Pressures,Hydrogen Standards,CNG Fill Type Code,CNG PSI,CNG Vehicle Class,LNG Vehicle Class,EV On-Site Renewable Source,Restricted Access
0,CNG,Spire - Montgomery Operations Center,2951 Chestnut St,NaN,Montgomery,AL,36107,NaN,NaN,E,NaN,Private,NaN,NaN,NaN,B,3600,NaN,NaN,NaN,NaN,NaN,NaN,200-9,32.367916,-86.267021,2022-06-14,17,2022-06-14 16:22:47 UTC,T,NaN,NaN,2010-12-01,NaN,MD,NaN,NaN,NaN,US,NaN,NaN,NaN,Privé,NaN,private,NaN,NaN,STANDALONE_STATION,NaN,NONE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,3600,MD,NaN,NaN,NaN
1,CNG,PS Energy - Atlanta,340 Whitehall St,"From I-7585 N, exit 91 to Central Ave, left on...",Atlanta,GA,30303,NaN,770-350-3000,E,NaN,Public - Card key at all times,24 hours daily,Comdata FleetOne FuelMan Voyager Wright_Exp,NaN,Q,3600,NaN,NaN,NaN,NaN,NaN,NaN,200-8,33.745843,-84.398837,2021-08-04,42,2022-02-10 19:42:29 UTC,P,NaN,NaN,1994-07-15,NaN,MD,NaN,NaN,NaN,US,NaN,NaN,NaN,Public - Carte-clé en tout temps,NaN,public,KEY_ALWAYS,NaN,STANDALONE_STATION,1.0,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q,3600,MD,NaN,NaN,False
2,CNG,Metropolitan Atlanta Rapid Transit Authority,2424 Piedmont Rd NE,NaN,Atlanta,GA,30324,NaN,NaN,E,NaN,Private - Government only,NaN,NaN,NaN,Q,3000,NaN,NaN,NaN,NaN,NaN,NaN,200-8,33.821911,-84.367461,2021-08-04,45,2022-02-10 19:42:29 UTC,LG,NaN,NaN,1996-12-15,NaN,LD,NaN,NaN,NaN,US,NaN,NaN,NaN,Privé - Réservé au gouvernement,NaN,private,GOVERNMENT,NaN,FLEET_GARAGE,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q,3000,LD,NaN,NaN,NaN

In [29]:
df2.shape

(70406, 65)

In [30]:
df2.describe()

,Plus4,EV Level1 EVSE Num,EV Level2 EVSE Num,EV DC Fast Count,Latitude,Longitude,ID,Federal Agency ID,CNG Dispenser Num,CNG Total Compression Capacity,CNG Storage Capacity
count,0.0,286.000000,54144.000000,8307.000000,70406.000000,70406.000000,70406.000000,955.000000,1039.000000,708.000000,357.000000
mean,NaN,3.461538,2.315289,3.576381,38.929309,-96.061447,148730.326066,13.905759,2.731473,873.766949,47866.787115
std,NaN,6.548356,3.157387,4.129470,5.628458,19.545273,54261.672118,6.767439,8.333492,1032.371466,54327.698853
min,NaN,1.000000,1.000000,1.000000,0.000000,-159.788556,17.000000,2.000000,0.000000,2.000000,0.000000
25%,NaN,1.000000,2.000000,1.000000,34.182981,-117.860563,113723.250000,8.000000,1.000000,215.750000,30000.000000
50%,NaN,1.000000,2.000000,2.000000,39.105989,-92.002897,165247.500000,14.000000,2.000000,632.000000,36000.000000
75%,NaN,2.000000,2.000000,4.000000,42.702185,-78.881493,190653.750000,17.000000,2.000000,1100.000000,60000.000000
max,NaN,51.000000,311.000000,56.000000,64.852466,40.432278,224382.000000,60.000000,202.000000,10620.000000,593136.000000

In [31]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70406 entries, 0 to 70405
Data columns (total 65 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Fuel Type Code                    70406 non-null  object
 1   Station Name                      70406 non-null  object
 2   Street Address                    70405 non-null  object
 3   Intersection Directions           4493 non-null   object
 4   City                              70406 non-null  object
 5   State                             70406 non-null  object
 6   ZIP                               70405 non-null  object
 7   Plus4                             0 non-null      float64
 8   Station Phone                     65204 non-null  object
 9   Status Code                       70406 non-null  object
 10  Expected Date                     1218 non-null   object
 11  Groups With Access Code           70406 non-null  object
 12  Access Days Time                  66628 non-null  object
 13  Cards Accepted                    11289 non-null  object
 14  BD Blends                         1217 non-null   object
 15  NG Fill Type Code                 1603 non-null   object
 16  NG PSI                            1597 non-null   object
 17  EV Level1 EVSE Num                286 non-null    float64
 18  EV Level2 EVSE Num                54144 non-null  float64
 19  EV DC Fast Count                  8307 non-null   float64
 20  EV Other Info                     49 non-null     object
 21  EV Network                        60907 non-null  object
 22  EV Network Web                    50305 non-null  object
 23  Geocode Status                    70391 non-null  object
 24  Latitude                          70406 non-null  float64
 25  Longitude                         70406 non-null  float64
 26  Date Last Confirmed               70188 non-null  object
 27  ID                                70406 non-null  int64
 28  Updated At                        70406 non-null  object
 29  Owner Type Code                   30190 non-null  object
 30  Federal Agency ID                 955 non-null    float64
 31  Federal Agency Name               955 non-null    object
 32  Open Date                         69310 non-null  object
 33  Hydrogen Status Link              83 non-null     object
 34  NG Vehicle Class                  1780 non-null   object
 35  LPG Primary                       1867 non-null   object
 36  E85 Blender Pump                  4508 non-null   object
 37  EV Connector Types                60690 non-null  object
 38  Country                           70406 non-null  object
 39  Intersection Directions (French)  188 non-null    object
 40  Access Days Time (French)         6591 non-null   object
 41  BD Blends (French)                2 non-null      object
 42  Groups With Access Code (French)  70406 non-null  object
 43  Hydrogen Is Retail                117 non-null    object
 44  Access Code                       70406 non-null  object
 45  Access Detail Code                7423 non-null   object
 46  Federal Agency Code               955 non-null    object
 47  Facility Type                     27665 non-null  object
 48  CNG Dispenser Num                 1039 non-null   float64
 49  CNG On-Site Renewable Source      716 non-null    object
 50  CNG Total Compression Capacity    708 non-null    float64
 51  CNG Storage Capacity              357 non-null    float64
 52  LNG On-Site Renewable Source      62 non-null     object
 53  E85 Other Ethanol Blends          1458 non-null   object
 54  EV Pricing                        16961 non-null  object
 55  EV Pricing (French)               2032 non-null   object
 56  LPG Nozzle Types                  1826 non-null   object
 57  Hydrogen Pressures                116 non-null    object
 58  Hydrogen Standards                116 non-null    object
 59  CNG Fill Type Code                1603 non-null   object
 60  CNG PSI                           1597 non-null   object
 61  CNG Vehicle Class                 1622 non-null   object
 62  LNG Vehicle Class                 158 non-null    object
 63  EV On-Site Renewable Source       370 non-null    object
 64  Restricted Access                 53435 non-null  object
dtypes: float64(10), int64(1), object(54)
memory usage: 34.9+ MB

In [32]:
pd.set_option('display.max_rows', None)

In [33]:
df2.isnull().sum()

Fuel Type Code                          0
Station Name                            0
Street Address                          1
Intersection Directions             65913
City                                    0
State                                   0
ZIP                                     1
Plus4                               70406
Station Phone                        5202
Status Code                             0
Expected Date                       69188
Groups With Access Code                 0
Access Days Time                     3778
Cards Accepted                      59117
BD Blends                           69189
NG Fill Type Code                   68803
NG PSI                              68809
EV Level1 EVSE Num                  70120
EV Level2 EVSE Num                  16262
EV DC Fast Count                    62099
EV Other Info                       70357
EV Network                           9499
EV Network Web                      20101
Geocode Status                         15
Latitude                                0
Longitude                               0
Date Last Confirmed                   218
ID                                      0
Updated At                              0
Owner Type Code                     40216
Federal Agency ID                   69451
Federal Agency Name                 69451
Open Date                            1096
Hydrogen Status Link                70323
NG Vehicle Class                    68626
LPG Primary                         68539
E85 Blender Pump                    65898
EV Connector Types                   9716
Country                                 0
Intersection Directions (French)    70218
Access Days Time (French)           63815
BD Blends (French)                  70404
Groups With Access Code (French)        0
Hydrogen Is Retail                  70289
Access Code                             0
Access Detail Code                  62983
Federal Agency Code                 69451
Facility Type                       42741
CNG Dispenser Num                   69367
CNG On-Site Renewable Source        69690
CNG Total Compression Capacity      69698
CNG Storage Capacity                70049
LNG On-Site Renewable Source        70344
E85 Other Ethanol Blends            68948
EV Pricing                          53445
EV Pricing (French)                 68374
LPG Nozzle Types                    68580
Hydrogen Pressures                  70290
Hydrogen Standards                  70290
CNG Fill Type Code                  68803
CNG PSI                             68809
CNG Vehicle Class                   68784
LNG Vehicle Class                   70248
EV On-Site Renewable Source         70036
Restricted Access                   16971
dtype: int64

### Diccionario

1. **Fuel Type Code:** Código del tipo de combustible.
2. **Station Name:** Nombre de la estación.
3. **Street Address:** Dirección de la calle.
4. **Intersection Directions:** Direcciones de la intersección.
5. **City:** Ciudad.
6. **State:** Estado.
7. **ZIP:** Código postal.
8. **Plus4:** Código postal adicional.
9. **Station Phone:** Número de teléfono de la estación.
10. **Status Code:** Código de estado.
11. **Expected Date:** Fecha esperada.
12. **Groups With Access Code:** Código de grupos con acceso.
13. **Access Days Time:** Días y horas de acceso.
14. **Cards Accepted:** Tarjetas aceptadas.
15. **BD Blends:** Mezclas de BD.
16. **NG Fill Type Code:** Código de tipo de llenado de gas natural.
17. **NG PSI:** Presión de gas natural en PSI.
18. **EV Level1 EVSE Num:** Número de estaciones de carga de vehículos eléctricos de nivel 1.
19. **EV Level2 EVSE Num:** Número de estaciones de carga de vehículos eléctricos de nivel 2.
20. **EV DC Fast Count:** Cantidad de estaciones de carga rápida para vehículos eléctricos.
21. **EV Other Info:** Otra información sobre vehículos eléctricos.
22. **EV Network:** Red de vehículos eléctricos.
23. **EV Network Web:** Sitio web de la red de vehículos eléctricos.
24. **Geocode Status:** Estado del geocódigo.
25. **Latitude:** Latitud.
26. **Longitude:** Longitud.
27. **Date Last Confirmed:** Fecha de última confirmación.
28. **ID:** Identificación.
29. **Updated At:** Actualizado en.
30. **Owner Type Code:** Código del tipo de propietario.
31. **Federal Agency ID:** Identificación de la agencia federal.
32. **Federal Agency Name:** Nombre de la agencia federal.
33. **Open Date:** Fecha de apertura.
34. **Hydrogen Status Link:** Enlace de estado del hidrógeno.
35. **NG Vehicle Class:** Clase de vehículo de gas natural.
36. **LPG Primary:** Gas licuado de petróleo primario.
37. **E85 Blender Pump:** Bomba mezcladora de E85.
38. **EV Connector Types:** Tipos de conectores para vehículos eléctricos.
39. **Country:** País.
40. **Intersection Directions (French):** Direcciones de la intersección en francés.
41. **Access Days Time (French):** Días y horas de acceso en francés.
42. **BD Blends (French):** Mezclas de BD en francés.
43. **Groups With Access Code (French):** Código de grupos con acceso en francés.
44. **Hydrogen Is Retail:** El hidrógeno es minorista.
45. **Access Code:** Código de acceso.
46. **Access Detail Code:** Código de detalle de acceso.
47. **Federal Agency Code:** Código de la agencia federal.
48. **Facility Type:** Tipo de instalación.
49. **CNG Dispenser Num:** Número de dispensadores de CNG.
50. **CNG On-Site Renewable Source:** Fuente renovable de CNG en el lugar.
51. **CNG Total Compression Capacity:** Capacidad total de compresión de CNG.
52. **CNG Storage Capacity:** Capacidad de almacenamiento de CNG.
53. **LNG On-Site Renewable Source:** Fuente renovable de LNG en el lugar.
54. **E85 Other Ethanol Blends:** Otras mezclas de etanol E85.
55. **EV Pricing:** Precio de carga para vehículos eléctricos.
56. **EV Pricing (French):** Precio de carga para vehículos eléctricos en francés.
57. **LPG Nozzle Types:** Tipos de boquillas de gas licuado de petróleo.
58. **Hydrogen Pressures:** Presiones de hidrógeno.
59. **Hydrogen Standards:** Estándares de hidrógeno.
60. **CNG Fill Type Code:** Código de tipo de llenado de CNG.
61. **CNG PSI:** Presión de CNG.
62. **CNG Vehicle Class:** Clase de vehículo de CNG.
63. **LNG Vehicle Class:** Clase de vehículo de LNG.
64. **EV On-Site Renewable Source:** Fuente renovable de vehículos eléctricos en el lugar.
65. **Restricted Access:** Acceso restringido.

Después de una exhaustiva revisión del diccionario de variables y una consideración detallada de la magnitud de los valores nulos en nuestro conjunto de datos, hemos tomado decisiones críticas para optimizar nuestro conjunto de datos. La optimización se basa en dos criterios fundamentales: la abundancia de valores faltantes y la relevancia de cada variable para nuestro análisis. A continuación, detallamos las columnas que hemos decidido eliminar y los motivos detrás de cada elección:

Variables a Eliminar:

- Intersection Directions (Direcciones de Intersección): Presenta una gran cantidad de valores faltantes y puede carecer de relevancia crucial para nuestro análisis general.
- Plus4: Todos los valores de esta columna son NaN, lo que indica que no aporta información útil.
- Expected Date (Fecha Esperada): Contiene un número significativo de valores faltantes, lo cual podría afectar la integridad de nuestros resultados.
- BD Blends: Mezclas de BD (valor del combustible de origen biológico) disponibles.
- NG Fill Type Code: Código del tipo de carga de gas natural.
- NG PSI: Presión de llenado de gas natural.
- EV Level1 EVSE Num: Número de puntos de carga de vehículos eléctricos de nivel 1.
- EV DC Fast Count: Cantidad de puntos de carga rápida para vehículos eléctricos.
- EV Other Info: Otra información relevante sobre la carga de vehículos eléctricos.
- Hydrogen Status Link: Enlace de estado del hidrógeno.
- NG Vehicle Class: Clase de vehículos a gas natural.
- LPG Primary: Tipo de gas licuado de petróleo (LPG) primario.
- E85 Blender Pump: Bomba mezcladora de E85 (etanol) disponible.
- Intersection Directions (French): Instrucciones para llegar a la estación en francés.
- Access Days Time (French): Días y horarios de acceso a la estación en francés.
- BD Blends (French): Mezclas de BD (valor del combustible de origen biológico) disponibles en francés.
- Hydrogen Is Retail: Indicación de si el hidrógeno está disponible para venta al público.
- Access Detail Code: Código de acceso a la estación.
- Federal Agency Code: Código de la agencia federal.
- CNG Dispenser Num: Número de dispensadores de gas natural comprimido (GNC).
- CNG On-Site Renewable Source: Fuente renovable de gas natural comprimido (GNC) en el sitio.
- CNG Total Compression Capacity: Capacidad total de compresión de gas natural comprimido (GNC).
- CNG Storage Capacity: Capacidad de almacenamiento de gas natural comprimido (GNC).
- LNG On-Site Renewable Source: Fuente renovable de gas natural licuado (GNL) en el sitio.
- E85 Other Ethanol Blends: Otras mezclas de etanol E85 disponibles.
- EV Pricing (French): Información sobre la tarificación de la carga de vehículos eléctricos en francés.
- LPG Nozzle Types: Tipos de boquillas de gas licuado de petróleo (GPL).
- Hydrogen Pressures: Presiones de hidrógeno en la estación.
- Hydrogen Standards: Estándares de hidrógeno utilizados en la estación.
- CNG Fill Type Code: Código del tipo de llenado de gas natural comprimido (GNC).
- CNG PSI: Presión de llenado de gas natural comprimido (CNG).
- EV On-Site Renewable Source: Fuente renovable de energía eléctrica en el sitio para cargar vehículos eléctricos.
- Federal Agency ID.
- Federal Agency Name.
- Hydrogen Status Link: Tienen muchos valores faltantes y podrían no ser relevantes para el análisis.
- Owner Type Code: Tiene una cantidad considerable de valores faltantes.
- Restricted Access: Tiene una cantidad considerable de valores faltantes.
- Cards Accepted (Tarjetas Aceptadas): Información sobre las tarjetas de pago aceptadas en la estación.
- Facility Type (Tipo de Instalación): Indica el tipo de instalación, por ejemplo, estación de servicio, aparcamiento, etc.
- EV Pricing (Tarificación de Carga de Vehículos Eléctricos): Proporciona detalles sobre la tarificación de la carga de vehículos eléctricos.
- CNG Vehicle Class (Clase de Vehículos para Gas Natural Comprimido - CNG): Especifica la clase de vehículos diseñados para utilizar gas natural comprimido.
- LNG Vehicle Class (Clase de Vehículos para Gas Natural Licuado - LNG): Indica la clase de vehículos diseñados para utilizar gas natural licuado.

Este proceso de depuración garantiza que nos enfoquemos en las variables más significativas para nuestro análisis, excluyendo aquellas que tienen una alta proporción de valores faltantes o que carecen de relevancia para nuestro objetivo de estudio. De esta manera, aseguramos la calidad y la consistencia de nuestro conjunto de datos para llevar a cabo un análisis preciso y significativo.

In [34]:
# Lista de variables a eliminar
variables_a_eliminar = [
    'Intersection Directions',
    'Plus4',
    'Expected Date',
    'BD Blends',
    'NG Fill Type Code',
    'NG PSI',
    'EV DC Fast Count',
    'EV Other Info',
    'Station Phone',
    'Hydrogen Status Link',
    'NG Vehicle Class',
    'LPG Primary',
    'E85 Blender Pump',
    'Intersection Directions (French)',
    'Access Days Time (French)',
    'BD Blends (French)',
    'Hydrogen Is Retail',
    'Access Detail Code',
    'Federal Agency Code',
    'CNG Dispenser Num',
    'CNG On-Site Renewable Source',
    'CNG Total Compression Capacity',
    'CNG Storage Capacity',
    'LNG On-Site Renewable Source',
    'E85 Other Ethanol Blends',
    'EV Pricing (French)',
    'LPG Nozzle Types',
    'Hydrogen Pressures',
    'Hydrogen Standards',
    'CNG Fill Type Code',
    'CNG PSI',
    'EV On-Site Renewable Source',
    'Federal Agency ID',
    'Federal Agency Name',
    'Hydrogen Status Link',
    'Owner Type Code',
    'Restricted Access',
    'Cards Accepted',
    'Facility Type',
    'EV Pricing',
    'CNG Vehicle Class',
    'LNG Vehicle Class'
]

# Eliminar las variables del DataFrame
df2_filtered = df2.drop(columns=variables_a_eliminar)

Este código crea una nueva variable df2_filtered que contiene todas las columnas originales excepto las que queremos eliminar.

In [35]:
df2_filtered.head(3)

,Fuel Type Code,Station Name,Street Address,City,State,ZIP,Status Code,Groups With Access Code,Access Days Time,EV Level1 EVSE Num,EV Level2 EVSE Num,EV Network,EV Network Web,Geocode Status,Latitude,Longitude,Date Last Confirmed,ID,Updated At,Open Date,EV Connector Types,Country,Groups With Access Code (French),Access Code
0,CNG,Spire - Montgomery Operations Center,2951 Chestnut St,Montgomery,AL,36107,E,Private,NaN,NaN,NaN,NaN,NaN,200-9,32.367916,-86.267021,2022-06-14,17,2022-06-14 16:22:47 UTC,2010-12-01,NaN,US,Privé,private
1,CNG,PS Energy - Atlanta,340 Whitehall St,Atlanta,GA,30303,E,Public - Card key at all times,24 hours daily,NaN,NaN,NaN,NaN,200-8,33.745843,-84.398837,2021-08-04,42,2022-02-10 19:42:29 UTC,1994-07-15,NaN,US,Public - Carte-clé en tout temps,public
2,CNG,Metropolitan Atlanta Rapid Transit Authority,2424 Piedmont Rd NE,Atlanta,GA,30324,E,Private - Government only,NaN,NaN,NaN,NaN,NaN,200-8,33.821911,-84.367461,2021-08-04,45,2022-02-10 19:42:29 UTC,1996-12-15,NaN,US,Privé - Réservé au gouvernement,private

In [36]:
df2_filtered.isnull().sum()

Fuel Type Code                          0
Station Name                            0
Street Address                          1
City                                    0
State                                   0
ZIP                                     1
Status Code                             0
Groups With Access Code                 0
Access Days Time                     3778
EV Level1 EVSE Num                  70120
EV Level2 EVSE Num                  16262
EV Network                           9499
EV Network Web                      20101
Geocode Status                         15
Latitude                                0
Longitude                               0
Date Last Confirmed                   218
ID                                      0
Updated At                              0
Open Date                            1096
EV Connector Types                   9716
Country                                 0
Groups With Access Code (French)        0
Access Code                             0
dtype: int64

In [37]:
df2_filtered.shape

(70406, 24)


Después de realizar un análisis exhaustivo de nuestro conjunto de datos, observamos que aún persisten variables con una cantidad considerable de valores faltantes. A pesar de esta situación, hemos decidido retener estas variables por el momento. En el contexto de la extensión de nuestro conjunto de datos y considerando la magnitud de la información disponible, hemos llegado a la conclusión de que la cantidad de valores faltantes no afecta significativamente la integridad y representatividad del análisis.

Es importante señalar que, si bien existe una cantidad apreciable de valores nulos en algunas variables, no consideramos que esto comprometa la validez general del conjunto de datos para nuestros propósitos actuales. La decisión de retener estas variables se basa en la premisa de que la información contenida en ellas podría aportar valor al análisis global, y la cantidad de datos disponibles aún es suficiente para realizar interpretaciones significativas.

Con esta consideración en mente, procedemos a cargar y utilizar nuestro conjunto de datos actualizado (df2_filtered), confiando en que la información disponible será suficiente para abordar nuestras preguntas de investigación y objetivos analíticos.

In [38]:
# Especifica el nombre del archivo
nombre_del_archivo = 'Electric and Alternative Fuel Charging Stations cleaned.csv'

# Guarda el DataFrame en el archivo CSV
df2_filtered.to_csv('datasets/datasets_cleaned/' + nombre_del_archivo, index=False, encoding='utf-8')
print(f'Se ha guardado el archivo {nombre_del_archivo}', 'en la carpeta datasets_cleaned')

Se ha guardado el archivo Electric and Alternative Fuel Charging Stations cleaned.csv en la carpeta datasets_cleaned

# Dataset 3: ElectricCarData_Clean

In [39]:
df3 = pd.read_csv('datasets/datasets_originales/ElectricCarData_Clean.csv')

In [40]:
df3.head(3)

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440

In [41]:
df3['Brand'] = df3['Brand'].str.strip().str.lower()
tesla_df = df3[df3['Brand'] == 'tesla']

In [42]:
tesla_df

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
8,tesla,Model 3 Standard Range Plus,5.6,225,310,153,650,Yes,RWD,Type 2 CCS,Sedan,D,5,46380
21,tesla,Model Y Long Range Dual Motor,5.1,217,425,171,930,Yes,AWD,Type 2 CCS,SUV,D,7,58620
24,tesla,Model 3 Long Range Performance,3.4,261,435,167,910,Yes,AWD,Type 2 CCS,Sedan,D,5,61480
33,tesla,Cybertruck Tri Motor,3.0,210,750,267,710,Yes,AWD,Type 2 CCS,Pickup,N,6,75000
40,tesla,Model S Long Range,3.8,250,515,184,560,Yes,AWD,Type 2,Liftback,F,5,79990
51,tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000
54,tesla,Model X Long Range,4.6,250,450,211,490,Yes,AWD,Type 2,SUV,F,7,85990
59,tesla,Model S Performance,2.5,261,505,188,550,Yes,AWD,Type 2,Liftback,F,5,96990
61,tesla,Model Y Long Range Performance,3.7,241,410,177,900,Yes,AWD,Type 2 CCS,SUV,D,7,65620
67,tesla,Cybertruck Dual Motor,5.0,190,460,261,710,Yes,AWD,Type 2 CCS,Pickup,N,6,55000
81,tesla,Model X Performance,2.8,250,440,216,480,Yes,AWD,Type 2,SUV,F,7,102990
86,tesla,Cybertruck Single Motor,7.0,180,390,256,740,Yes,RWD,Type 2 CCS,Pickup,N,6,45000

In [43]:
df3.describe()

,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,Seats,PriceEuro
count,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000
mean,7.396117,179.194175,338.786408,189.165049,4.883495,55811.563107
std,3.017430,43.573030,126.014444,29.566839,0.795834,34134.665280
min,2.100000,123.000000,95.000000,104.000000,2.000000,20129.000000
25%,5.100000,150.000000,250.000000,168.000000,5.000000,34429.500000
50%,7.300000,160.000000,340.000000,180.000000,5.000000,45000.000000
75%,9.000000,200.000000,400.000000,203.000000,5.000000,65000.000000
max,22.400000,410.000000,970.000000,273.000000,7.000000,215000.000000

In [44]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            103 non-null    object
 1   Model            103 non-null    object
 2   AccelSec         103 non-null    float64
 3   TopSpeed_KmH     103 non-null    int64
 4   Range_Km         103 non-null    int64
 5   Efficiency_WhKm  103 non-null    int64
 6   FastCharge_KmH   103 non-null    object
 7   RapidCharge      103 non-null    object
 8   PowerTrain       103 non-null    object
 9   PlugType         103 non-null    object
 10  BodyStyle        103 non-null    object
 11  Segment          103 non-null    object
 12  Seats            103 non-null    int64
 13  PriceEuro        103 non-null    int64
dtypes: float64(1), int64(5), object(8)
memory usage: 11.4+ KB

In [45]:
df3.isnull().sum()

Brand              0
Model              0
AccelSec           0
TopSpeed_KmH       0
Range_Km           0
Efficiency_WhKm    0
FastCharge_KmH     0
RapidCharge        0
PowerTrain         0
PlugType           0
BodyStyle          0
Segment            0
Seats              0
PriceEuro          0
dtype: int64

### Diccionario

1. **Brand:** Marca del vehículo.
2. **Model:** Modelo específico del vehículo.
3. **AccelSec:** Aceleración de 0 a 100 km/h en segundos.
4. **TopSpeed_KmH:** Velocidad máxima en kilómetros por hora.
5. **Range_Km:** Rango de conducción en kilómetros.
6. **Efficiency_WhKm:** Eficiencia energética en vatios-hora por kilómetro.
7. **FastCharge_KmH:** Velocidad de carga rápida en kilómetros por hora.
8. **RapidCharge:** Capacidad de carga rápida (Sí/No).
9. **PowerTrain:** Tipo de tren motriz (tracción delantera, tracción trasera, tracción a las cuatro ruedas).
10. **PlugType:** Tipo de conector de carga.
11. **BodyStyle:** Estilo de carrocería del vehículo.
12. **Segment:** Segmento al que pertenece el vehículo.
13. **Seats:** Número de asientos en el vehículo.
14. **PriceEuro:** Precio del vehículo en euros.

Tras una evaluación inicial del conjunto de datos df3, se observa que no presenta valores nulos en ninguna de sus variables. Este hallazgo inicial es prometedor y sugiere que el conjunto de datos podría estar relativamente limpio y listo para su análisis.

En esta etapa, nos proponemos realizar un análisis más detallado de algunas variables clave presentes en df3. El objetivo es explorar posibles transformaciones, realizar limpiezas o identificar oportunidades para mejorar la calidad de los datos. Al centrarnos en variables específicas, buscamos asegurar la coherencia y fiabilidad de la información contenida en el conjunto de datos.

In [46]:
df3['Brand'].unique()

array(['tesla', 'volkswagen', 'polestar', 'bmw', 'honda', 'lucid',
       'peugeot', 'audi', 'mercedes', 'nissan', 'hyundai', 'porsche',
       'mg', 'mini', 'opel', 'skoda', 'volvo', 'kia', 'renault', 'mazda',
       'lexus', 'cupra', 'seat', 'lightyear', 'aiways', 'ds', 'citroen',
       'jaguar', 'ford', 'byton', 'sono', 'smart', 'fiat'], dtype=object)

In [47]:
df3['Model'].unique()

array(['Model 3 Long Range Dual Motor', 'ID.3 Pure', '2', 'iX3 ', 'e ',
       'Air ', 'e-Golf ', 'e-208 ', 'Model 3 Standard Range Plus',
       'Q4 e-tron ', 'EQC 400 4MATIC', 'Leaf ', 'Kona Electric 64 kWh',
       'i4 ', 'IONIQ Electric', 'ID.3 Pro S', 'Taycan Turbo S', 'e-Up! ',
       'ZS EV', 'Cooper SE ', 'Corsa-e ', 'Model Y Long Range Dual Motor',
       'Enyaq iV 50', 'e-tron GT ', 'Model 3 Long Range Performance',
       'ID.4 ', 'ID.3 Pro', 'XC40 P8 AWD Recharge', 'i3 120 Ah',
       'e-2008 SUV ', 'e-tron 50 quattro', 'e-Niro 64 kWh',
       'Zoe ZE50 R110', 'Cybertruck Tri Motor', 'MX-30 ', 'Leaf e+',
       'UX 300e', 'el-Born ', 'Zoe ZE50 R135', 'EQA ',
       'Model S Long Range', 'Kona Electric 39 kWh',
       'e-tron Sportback 55 quattro', 'CITIGOe iV ', 'Mii Electric ',
       'e-Soul 64 kWh', 'Ampera-e ', 'Taycan 4S', 'One ', 'U5 ',
       'e-tron 55 quattro', 'Roadster ', 'Mokka-e ', 'Enyaq iV 80',
       'Model X Long Range', 'e Advance', '3 Crossback E-Tense',
       'Twingo ZE', 'e-C4 ', 'Model S Performance', 'Zoe ZE40 R110',
       'Model Y Long Range Performance', 'Ariya 87kWh', 'I-Pace ',
       'Mustang Mach-E ER RWD', 'Taycan 4S Plus', 'e-NV200 Evalia ',
       'Cybertruck Dual Motor', 'Kangoo Maxi ZE 33',
       'Mustang Mach-E ER AWD', 'i3s 120 Ah', 'Enyaq iV 80X',
       'Taycan Cross Turismo ', 'M-Byte 95 kWh 4WD', 'Sion ',
       'e-Niro 39 kWh', 'Q4 Sportback e-tron ', 'EQ forfour ',
       'Mustang Mach-E SR AWD', 'Taycan Turbo', 'ID.3 1st',
       'Model X Performance', 'EQ fortwo coupe', 'Mustang Mach-E SR RWD',
       'EQV 300 Long', '500e Hatchback', 'Cybertruck Single Motor',
       'e-tron Sportback 50 quattro', 'Enyaq iV vRS', 'Enyaq iV 60',
       'e-tron S 55 quattro', 'EQ fortwo cabrio', 'Ariya e-4ORCE 87kWh',
       '500e Convertible', 'ID.3 Pro Performance', 'e-Soul 39 kWh',
       'M-Byte 72 kWh 2WD', 'Ariya 63kWh',
       'e-tron S Sportback 55 quattro', 'Ariya e-4ORCE 63kWh',
       'Ariya e-4ORCE 87kWh Performance', 'M-Byte 95 kWh 2WD'],
      dtype=object)

In [48]:
print(sorted(df3['TopSpeed_KmH'].unique()))

[123, 130, 135, 140, 144, 145, 150, 155, 157, 160, 165, 167, 180, 190, 200, 210, 217, 225, 233, 240, 241, 250, 260, 261, 410]

In [49]:
print(sorted(df3['Range_Km'].unique()))

[95, 100, 130, 160, 170, 180, 185, 190, 195, 220, 225, 230, 235, 250, 255, 270, 275, 280, 290, 295, 310, 315, 320, 325, 330, 335, 340, 350, 360, 365, 370, 375, 380, 385, 390, 400, 410, 420, 425, 430, 435, 440, 450, 460, 505, 515, 575, 610, 750, 970]

In [50]:
df3['Efficiency_WhKm'].unique()

array([161, 167, 181, 206, 168, 180, 164, 153, 193, 216, 160, 178, 175,
       223, 166, 156, 171, 179, 197, 183, 200, 231, 173, 165, 267, 172,
       184, 154, 228, 195, 104, 188, 237, 176, 211, 177, 198, 232, 261,
       194, 209, 217, 244, 215, 273, 256, 219, 270, 207, 170, 222, 191,
       258, 238], dtype=int64)

In [51]:
df3['FastCharge_KmH'].unique()

array(['940', '250', '620', '560', '190', '220', '420', '650', '540',
       '440', '230', '380', '210', '590', '780', '170', '260', '930',
       '850', '910', '490', '470', '270', '450', '350', '710', '240',
       '390', '570', '610', '340', '730', '920', '-', '550', '900', '520',
       '430', '890', '410', '770', '460', '360', '810', '480', '290',
       '330', '740', '510', '320', '500'], dtype=object)

Al observar la variable 'TopSpeed_KmH', notamos la presencia del valor '-', el cual interpretamos como un indicativo de datos faltantes. Para facilitar futuros análisis numéricos y cálculos, decidimos reemplazar este valor con el número cero (0). Este enfoque nos permite gestionar de manera consistente los valores nulos y asegurarnos de que no afecten las operaciones matemáticas.

In [52]:
df3['FastCharge_KmH'] = df3['FastCharge_KmH'].replace('-', 0).astype(int)

In [53]:
df3['FastCharge_KmH'].unique()

array([940, 250, 620, 560, 190, 220, 420, 650, 540, 440, 230, 380, 210,
       590, 780, 170, 260, 930, 850, 910, 490, 470, 270, 450, 350, 710,
       240, 390, 570, 610, 340, 730, 920,   0, 550, 900, 520, 430, 890,
       410, 770, 460, 360, 810, 480, 290, 330, 740, 510, 320, 500])

In [54]:
df3['RapidCharge'].unique()

array(['Yes', 'No'], dtype=object)

In [55]:
df3['PowerTrain'].unique()

array(['AWD', 'RWD', 'FWD'], dtype=object)

In [56]:
df3['PlugType'].unique()

array(['Type 2 CCS', 'Type 2 CHAdeMO', 'Type 2', 'Type 1 CHAdeMO'],
      dtype=object)

CCS (Combo): Este es un conector de carga combinada que integra un conector de carga rápida con un conector Tipo 1 o Tipo 2. Se utiliza principalmente en América del Norte y Europa.

Tipo 2 (Mennekes o IEC 62196): Ampliamente utilizado en Europa y otras regiones, este conector es conocido por ser más versátil y admite carga de corriente alterna y continua.

CHAdeMO: Este conector de carga rápida se utiliza comúnmente en vehículos eléctricos japoneses y algunos modelos en otras partes del mundo. tipo 1 y tipo 2.

In [57]:
df3['BodyStyle'].unique()

array(['Sedan', 'Hatchback', 'Liftback', 'SUV', 'Pickup', 'MPV', 'Cabrio',
       'SPV', 'Station'], dtype=object)

In [58]:
df3['Segment'].unique()

array(['D', 'C', 'B', 'F', 'A', 'E', 'N', 'S'], dtype=object)

In [59]:
df3['Seats'].unique()

array([5, 4, 7, 6, 2], dtype=int64)

In [60]:
print(sorted(df3['PriceEuro'].unique()))

[20129, 21387, 21421, 22030, 24534, 24565, 24790, 25500, 29146, 29234, 29682, 30000, 31184, 31681, 31900, 32646, 32997, 33000, 33133, 33246, 33971, 34361, 34400, 34459, 34900, 35000, 35575, 35921, 36057, 36837, 37237, 37422, 37500, 37900, 38000, 38017, 38105, 38987, 40000, 40795, 40936, 41526, 41906, 45000, 46380, 46900, 47500, 50000, 53500, 54000, 54475, 55000, 55480, 56440, 57500, 58620, 60437, 61480, 62000, 62900, 64000, 65000, 65620, 67358, 68040, 69484, 69551, 70631, 75000, 75351, 79445, 79990, 81639, 85990, 93800, 96050, 96990, 102945, 102990, 105000, 109302, 125000, 148301, 149000, 150000, 180781, 215000]

Después de un minucioso estudio y análisis de las variables en nuestro nuevo conjunto de datos ElectricCarData_Clean, hemos llevado a cabo ajustes necesarios, especialmente en la variable FastCharge_KmH, donde realizamos una pequeña modificación en los valores nulos para mejorar la integridad de nuestros datos.

En una revisión completa de las demás variables, podemos informar que no hemos encontrado valores nulos en ninguna de ellas. Este hallazgo respalda la calidad y la integridad general de nuestro conjunto de datos en esta primera instancia.

Consideramos cada variable en ElectricCarData_Clean como relevante para nuestro análisis.

In [61]:
# Especifica el nombre del archivo
nombre_del_archivo = 'ElectricCarData_Cleaned.csv'

# Guarda el DataFrame en el archivo CSV
df3.to_csv('datasets/datasets_cleaned/' + nombre_del_archivo, index=False, encoding='utf-8')
print(f'Se ha guardado el archivo {nombre_del_archivo}', 'en la carpeta datasets_cleaned')

Se ha guardado el archivo ElectricCarData_Cleaned.csv en la carpeta datasets_cleaned

# Dataset 4: ElectricCarData_Norm

In [62]:
df4 = pd.read_csv('datasets/datasets_originales/ElectricCarData_Norm.csv')

In [63]:
df4.head(3)

,Brand,Model,Accel,TopSpeed,Range,Efficiency,FastCharge,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6 sec,233 km/h,450 km,161 Wh/km,940 km/h,Rapid charging possible,All Wheel Drive,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0 sec,160 km/h,270 km,167 Wh/km,250 km/h,Rapid charging possible,Rear Wheel Drive,Type 2 CCS,Hatchback,C,5,30000
2,Polestar,2,4.7 sec,210 km/h,400 km,181 Wh/km,620 km/h,Rapid charging possible,All Wheel Drive,Type 2 CCS,Liftback,D,5,56440

In [64]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Brand        103 non-null    object
 1   Model        103 non-null    object
 2   Accel        103 non-null    object
 3   TopSpeed     103 non-null    object
 4   Range        103 non-null    object
 5   Efficiency   103 non-null    object
 6   FastCharge   103 non-null    object
 7   RapidCharge  103 non-null    object
 8   PowerTrain   103 non-null    object
 9   PlugType     103 non-null    object
 10  BodyStyle    103 non-null    object
 11  Segment      103 non-null    object
 12  Seats        103 non-null    int64
 13  PriceEuro    103 non-null    int64
dtypes: int64(2), object(12)
memory usage: 11.4+ KB

In [65]:
df4.isnull().sum()

Brand          0
Model          0
Accel          0
TopSpeed       0
Range          0
Efficiency     0
FastCharge     0
RapidCharge    0
PowerTrain     0
PlugType       0
BodyStyle      0
Segment        0
Seats          0
PriceEuro      0
dtype: int64

In [66]:
df4.head(3)

,Brand,Model,Accel,TopSpeed,Range,Efficiency,FastCharge,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6 sec,233 km/h,450 km,161 Wh/km,940 km/h,Rapid charging possible,All Wheel Drive,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0 sec,160 km/h,270 km,167 Wh/km,250 km/h,Rapid charging possible,Rear Wheel Drive,Type 2 CCS,Hatchback,C,5,30000
2,Polestar,2,4.7 sec,210 km/h,400 km,181 Wh/km,620 km/h,Rapid charging possible,All Wheel Drive,Type 2 CCS,Liftback,D,5,56440

### Diccionario

1. **Brand:** Marca del vehículo.
2. **Model:** Modelo específico del vehículo.
3. **Accel:** Aceleración de 0 a 100 km/h en segundos.
4. **TopSpeed:** Velocidad máxima en kilómetros por hora.
5. **Range:** Rango de conducción en kilómetros.
6. **Efficiency:** Eficiencia energética en vatios-hora por kilómetro.
7. **FastCharge:** Velocidad de carga rápida en kilómetros por hora.
8. **RapidCharge:** Capacidad de carga rápida (Posible/No posible).
9. **PowerTrain:** Tipo de tren motriz (tracción delantera, tracción trasera, tracción a las cuatro ruedas).
10. **PlugType:** Tipo de conector de carga.
11. **BodyStyle:** Estilo de carrocería del vehículo.
12. **Segment:** Segmento al que pertenece el vehículo.
13. **Seats:** Número de asientos en el vehículo.
14. **PriceEuro:** Precio del vehículo en euros.

In [67]:
df4['Brand'].unique()

array(['Tesla ', 'Volkswagen ', 'Polestar ', 'BMW ', 'Honda ', 'Lucid ',
       'Peugeot ', 'Audi ', 'Mercedes ', 'Nissan ', 'Hyundai ',
       'Porsche ', 'MG ', 'Mini ', 'Opel ', 'Skoda ', 'Volvo ', 'Kia ',
       'Renault ', 'Mazda ', 'Lexus ', 'CUPRA ', 'SEAT ', 'Lightyear ',
       'Aiways ', 'DS ', 'Citroen ', 'Jaguar ', 'Ford ', 'Byton ',
       'Sono ', 'Smart ', 'Fiat '], dtype=object)

In [68]:
df4['Model'].unique()

array(['Model 3 Long Range Dual Motor', 'ID.3 Pure', '2', 'iX3 ', 'e ',
       'Air ', 'e-Golf ', 'e-208 ', 'Model 3 Standard Range Plus',
       'Q4 e-tron ', 'EQC 400 4MATIC', 'Leaf ', 'Kona Electric 64 kWh',
       'i4 ', 'IONIQ Electric', 'ID.3 Pro S', 'Taycan Turbo S', 'e-Up! ',
       'ZS EV', 'Cooper SE ', 'Corsa-e ', 'Model Y Long Range Dual Motor',
       'Enyaq iV 50', 'e-tron GT ', 'Model 3 Long Range Performance',
       'ID.4 ', 'ID.3 Pro', 'XC40 P8 AWD Recharge', 'i3 120 Ah',
       'e-2008 SUV ', 'e-tron 50 quattro', 'e-Niro 64 kWh',
       'Zoe ZE50 R110', 'Cybertruck Tri Motor', 'MX-30 ', 'Leaf e+',
       'UX 300e', 'el-Born ', 'Zoe ZE50 R135', 'EQA ',
       'Model S Long Range', 'Kona Electric 39 kWh',
       'e-tron Sportback 55 quattro', 'CITIGOe iV ', 'Mii Electric ',
       'e-Soul 64 kWh', 'Ampera-e ', 'Taycan 4S', 'One ', 'U5 ',
       'e-tron 55 quattro', 'Roadster ', 'Mokka-e ', 'Enyaq iV 80',
       'Model X Long Range', 'e Advance', '3 Crossback E-Tense',
       'Twingo ZE', 'e-C4 ', 'Model S Performance', 'Zoe ZE40 R110',
       'Model Y Long Range Performance', 'Ariya 87kWh', 'I-Pace ',
       'Mustang Mach-E ER RWD', 'Taycan 4S Plus', 'e-NV200 Evalia ',
       'Cybertruck Dual Motor', 'Kangoo Maxi ZE 33',
       'Mustang Mach-E ER AWD', 'i3s 120 Ah', 'Enyaq iV 80X',
       'Taycan Cross Turismo ', 'M-Byte 95 kWh 4WD', 'Sion ',
       'e-Niro 39 kWh', 'Q4 Sportback e-tron ', 'EQ forfour ',
       'Mustang Mach-E SR AWD', 'Taycan Turbo', 'ID.3 1st',
       'Model X Performance', 'EQ fortwo coupe', 'Mustang Mach-E SR RWD',
       'EQV 300 Long', '500e Hatchback', 'Cybertruck Single Motor',
       'e-tron Sportback 50 quattro', 'Enyaq iV vRS', 'Enyaq iV 60',
       'e-tron S 55 quattro', 'EQ fortwo cabrio', 'Ariya e-4ORCE 87kWh',
       '500e Convertible', 'ID.3 Pro Performance', 'e-Soul 39 kWh',
       'M-Byte 72 kWh 2WD', 'Ariya 63kWh',
       'e-tron S Sportback 55 quattro', 'Ariya e-4ORCE 63kWh',
       'Ariya e-4ORCE 87kWh Performance', 'M-Byte 95 kWh 2WD'],
      dtype=object)

In [69]:
df4['Accel'].unique()

array(['4.6 sec', '10.0 sec', '4.7 sec', '6.8 sec', '9.5 sec', '2.8 sec',
       '9.6 sec', '8.1 sec', '5.6 sec', '6.3 sec', '5.1 sec', '7.9 sec',
       '4.0 sec', '9.7 sec', '11.9 sec', '8.2 sec', '7.3 sec', '3.5 sec',
       '3.4 sec', '7.5 sec', '9.0 sec', '4.9 sec', '8.5 sec', '7.8 sec',
       '11.4 sec', '3.0 sec', '6.5 sec', '5.0 sec', '3.8 sec', '9.9 sec',
       '5.7 sec', '12.3 sec', '2.1 sec', '8.8 sec', '8.3 sec', '8.7 sec',
       '12.6 sec', '2.5 sec', '3.7 sec', '7.6 sec', '4.8 sec', '7.0 sec',
       '14.0 sec', '22.4 sec', '6.0 sec', '6.9 sec', '5.5 sec', '9.8 sec',
       '12.7 sec', '3.2 sec', '11.6 sec', '6.6 sec', '6.2 sec', '4.5 sec',
       '5.9 sec'], dtype=object)

In [70]:
df4['TopSpeed'].unique()

array(['233 km/h', '160 km/h', '210 km/h', '180 km/h', '145 km/h',
       '250 km/h', '150 km/h', '225 km/h', '144 km/h', '167 km/h',
       '200 km/h', '165 km/h', '260 km/h', '130 km/h', '140 km/h',
       '217 km/h', '240 km/h', '261 km/h', '190 km/h', '135 km/h',
       '157 km/h', '155 km/h', '410 km/h', '241 km/h', '123 km/h'],
      dtype=object)

In [71]:
df4['Range'].unique()

array(['450 km', '270 km', '400 km', '360 km', '170 km', '610 km',
       '190 km', '275 km', '310 km', '370 km', '220 km', '250 km',
       '440 km', '375 km', '195 km', '185 km', '425 km', '290 km',
       '435 km', '420 km', '350 km', '235 km', '280 km', '315 km',
       '750 km', '180 km', '325 km', '515 km', '255 km', '380 km',
       '365 km', '335 km', '575 km', '970 km', '130 km', '505 km',
       '410 km', '460 km', '160 km', '430 km', '230 km', '385 km',
       '390 km', '225 km', '95 km', '340 km', '100 km', '330 km',
       '295 km', '320 km'], dtype=object)

In [72]:
df4['Efficiency'].unique()

array(['161 Wh/km', '167 Wh/km', '181 Wh/km', '206 Wh/km', '168 Wh/km',
       '180 Wh/km', '164 Wh/km', '153 Wh/km', '193 Wh/km', '216 Wh/km',
       '160 Wh/km', '178 Wh/km', '175 Wh/km', '223 Wh/km', '166 Wh/km',
       '156 Wh/km', '171 Wh/km', '179 Wh/km', '197 Wh/km', '183 Wh/km',
       '200 Wh/km', '231 Wh/km', '173 Wh/km', '165 Wh/km', '267 Wh/km',
       '172 Wh/km', '184 Wh/km', '154 Wh/km', '228 Wh/km', '195 Wh/km',
       '104 Wh/km', '188 Wh/km', '237 Wh/km', '176 Wh/km', '211 Wh/km',
       '177 Wh/km', '198 Wh/km', '232 Wh/km', '261 Wh/km', '194 Wh/km',
       '209 Wh/km', '217 Wh/km', '244 Wh/km', '215 Wh/km', '273 Wh/km',
       '256 Wh/km', '219 Wh/km', '270 Wh/km', '207 Wh/km', '170 Wh/km',
       '222 Wh/km', '191 Wh/km', '258 Wh/km', '238 Wh/km'], dtype=object)

In [73]:
df4['FastCharge'].unique()

array(['940 km/h', '250 km/h', '620 km/h', '560 km/h', '190 km/h',
       '220 km/h', '420 km/h', '650 km/h', '540 km/h', '440 km/h',
       '230 km/h', '380 km/h', '210 km/h', '590 km/h', '780 km/h',
       '170 km/h', '260 km/h', '930 km/h', '850 km/h', '910 km/h',
       '490 km/h', '470 km/h', '270 km/h', '450 km/h', '350 km/h',
       '710 km/h', '240 km/h', '390 km/h', '570 km/h', '610 km/h',
       '340 km/h', '730 km/h', '920 km/h', '-', '550 km/h', '900 km/h',
       '520 km/h', '430 km/h', '890 km/h', '410 km/h', '770 km/h',
       '460 km/h', '360 km/h', '810 km/h', '480 km/h', '290 km/h',
       '330 km/h', '740 km/h', '510 km/h', '320 km/h', '500 km/h'],
      dtype=object)

In [74]:
# Suponiendo que tu columna se llama 'TopSpeed_KmH' en tu DataFrame df3
df4['FastCharge'] = df4['FastCharge'].replace('-', '0 km/h')

In [75]:
df4['FastCharge'].unique()

array(['940 km/h', '250 km/h', '620 km/h', '560 km/h', '190 km/h',
       '220 km/h', '420 km/h', '650 km/h', '540 km/h', '440 km/h',
       '230 km/h', '380 km/h', '210 km/h', '590 km/h', '780 km/h',
       '170 km/h', '260 km/h', '930 km/h', '850 km/h', '910 km/h',
       '490 km/h', '470 km/h', '270 km/h', '450 km/h', '350 km/h',
       '710 km/h', '240 km/h', '390 km/h', '570 km/h', '610 km/h',
       '340 km/h', '730 km/h', '920 km/h', '0 km/h', '550 km/h',
       '900 km/h', '520 km/h', '430 km/h', '890 km/h', '410 km/h',
       '770 km/h', '460 km/h', '360 km/h', '810 km/h', '480 km/h',
       '290 km/h', '330 km/h', '740 km/h', '510 km/h', '320 km/h',
       '500 km/h'], dtype=object)

In [76]:
df4['RapidCharge'].unique()

array(['Rapid charging possible', 'Rapid charging not possible'],
      dtype=object)

In [77]:
df4['PowerTrain'].unique()

array(['All Wheel Drive', 'Rear Wheel Drive', 'Front Wheel Drive'],
      dtype=object)

In [78]:
df4['PlugType'].unique()

array(['Type 2 CCS', 'Type 2 CHAdeMO', 'Type 2', 'Type 1 CHAdeMO'],
      dtype=object)

In [79]:
df4['BodyStyle'].unique()

array(['Sedan', 'Hatchback', 'Liftback', 'SUV', 'Pickup', 'MPV', 'Cabrio',
       'SPV', 'Station'], dtype=object)

In [80]:
df4['Segment'].unique()

array(['D', 'C', 'B', 'F', 'A', 'E', 'N', 'S'], dtype=object)

In [81]:
df4['Seats'].unique()

array([5, 4, 7, 6, 2], dtype=int64)

In [82]:
df4['PriceEuro'].unique()

array([ 55480,  30000,  56440,  68040,  32997, 105000,  31900,  29682,
        46380,  55000,  69484,  29234,  40795,  65000,  34459,  40936,
       180781,  21421,  31681,  29146,  58620,  35000, 125000,  61480,
        45000,  33000,  60437,  38017,  34361,  67358,  38105,  31184,
        75000,  32646,  37237,  50000,  33133,  79990,  33971,  81639,
        24534,  20129,  36837,  41906, 102945, 149000,  36057,  79445,
       215000,  40000,  85990,  35921,  37422,  24790,  96990,  65620,
        75351,  54475, 109302,  33246,  38000,  62900,  41526, 150000,
        64000,  25500,  34400,  57500,  22030,  54000, 148301,  38987,
       102990,  21387,  46900,  70631,  34900,  69551,  47500,  37500,
        93800,  24565,  37900,  35575,  53500,  96050,  62000],
      dtype=int64)

In [83]:
# Especifica el nombre del archivo
nombre_del_archivo = 'ElectricCarData_Norm_Cleaned.csv'

# Guarda el DataFrame en el archivo CSV
df4.to_csv('datasets/datasets_cleaned/' + nombre_del_archivo, index=False, encoding='utf-8')
print(f'Se ha guardado el archivo {nombre_del_archivo}', 'en la carpeta datasets_cleaned')

Se ha guardado el archivo ElectricCarData_Norm_Cleaned.csv en la carpeta datasets_cleaned

# Dataset 5: Light Duty Vehicles

In [84]:
df5 = pd.read_csv('datasets/datasets_originales/Light Duty Vehicles.csv')

In [85]:
df5.head(3)

,Vehicle ID,Fuel ID,Fuel Configuration ID,Manufacturer ID,Category ID,Model,Model Year,Alternative Fuel Economy City,Alternative Fuel Economy Highway,Alternative Fuel Economy Combined,Conventional Fuel Economy City,Conventional Fuel Economy Highway,Conventional Fuel Economy Combined,Transmission Type,Engine Type,Engine Size,Engine Cylinder Count,Engine Description,Manufacturer,Manufacturer URL,Category,Fuel Code,Fuel,Fuel Configuration Name,Electric-Only Range,PHEV Total Range,PHEV Type,Notes,Drivetrain
0,13044,45,9.0,365,27,NSX,2022,NaN,NaN,NaN,21.0,22.0,21.0,Auto,SI,3.5L,6.0,3.5L V6,Acura,http://www.acura.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,AWD
1,12854,45,9.0,377,27,A3,2022,NaN,NaN,NaN,29.0,38.0,32.0,Auto,SI,2.0L,4.0,2.0L I4,Audi,http://progress.audiusa.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,FWD
2,12842,45,9.0,377,27,A3 quattro,2022,NaN,NaN,NaN,28.0,36.0,31.0,Auto,SI,2.0L,4.0,2.0L I4,Audi,http://progress.audiusa.com/,Sedan/Wagon,HYBR,Hybrid Electric,Hybrid Electric,NaN,NaN,NaN,NaN,AWD

In [86]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3008 entries, 0 to 3007
Data columns (total 29 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Vehicle ID                          3008 non-null   int64
 1   Fuel ID                             3008 non-null   int64
 2   Fuel Configuration ID               2973 non-null   float64
 3   Manufacturer ID                     3008 non-null   int64
 4   Category ID                         3008 non-null   int64
 5   Model                               3008 non-null   object
 6   Model Year                          3008 non-null   int64
 7   Alternative Fuel Economy City       1595 non-null   float64
 8   Alternative Fuel Economy Highway    1505 non-null   float64
 9   Alternative Fuel Economy Combined   467 non-null    float64
 10  Conventional Fuel Economy City      2044 non-null   float64
 11  Conventional Fuel Economy Highway   2046 non-null   float64
 12  Conventional Fuel Economy Combined  763 non-null    float64
 13  Transmission Type                   2924 non-null   object
 14  Engine Type                         2211 non-null   object
 15  Engine Size                         2874 non-null   object
 16  Engine Cylinder Count               2443 non-null   float64
 17  Engine Description                  1971 non-null   object
 18  Manufacturer                        3008 non-null   object
 19  Manufacturer URL                    2844 non-null   object
 20  Category                            3008 non-null   object
 21  Fuel Code                           3008 non-null   object
 22  Fuel                                3008 non-null   object
 23  Fuel Configuration Name             2973 non-null   object
 24  Electric-Only Range                 374 non-null    float64
 25  PHEV Total Range                    43 non-null     float64
 26  PHEV Type                           176 non-null    object
 27  Notes                               73 non-null     object
 28  Drivetrain                          329 non-null    object
dtypes: float64(10), int64(5), object(14)
memory usage: 681.6+ KB

In [87]:
df5.isnull().sum()

Vehicle ID                               0
Fuel ID                                  0
Fuel Configuration ID                   35
Manufacturer ID                          0
Category ID                              0
Model                                    0
Model Year                               0
Alternative Fuel Economy City         1413
Alternative Fuel Economy Highway      1503
Alternative Fuel Economy Combined     2541
Conventional Fuel Economy City         964
Conventional Fuel Economy Highway      962
Conventional Fuel Economy Combined    2245
Transmission Type                       84
Engine Type                            797
Engine Size                            134
Engine Cylinder Count                  565
Engine Description                    1037
Manufacturer                             0
Manufacturer URL                       164
Category                                 0
Fuel Code                                0
Fuel                                     0
Fuel Configuration Name                 35
Electric-Only Range                   2634
PHEV Total Range                      2965
PHEV Type                             2832
Notes                                 2935
Drivetrain                            2679
dtype: int64

In [88]:
df5.describe()

,Vehicle ID,Fuel ID,Fuel Configuration ID,Manufacturer ID,Category ID,Model Year,Alternative Fuel Economy City,Alternative Fuel Economy Highway,Alternative Fuel Economy Combined,Conventional Fuel Economy City,Conventional Fuel Economy Highway,Conventional Fuel Economy Combined,Engine Cylinder Count,Electric-Only Range,PHEV Total Range
count,3008.00000,3008.000000,2973.000000,3008.000000,3008.000000,3008.000000,1595.000000,1505.000000,467.000000,2044.000000,2046.000000,763.000000,2443.000000,374.000000,43.000000
mean,9424.59242,31.003989,4.907164,255.855718,24.988697,2014.493019,38.439298,37.392651,72.126338,22.781605,27.443206,27.832241,6.085960,148.251337,450.465116
std,4667.98027,18.311570,3.263154,64.474477,6.021677,6.722191,47.778798,42.724296,36.776309,10.794132,10.123663,10.265666,1.762977,128.708353,93.042578
min,1.00000,3.000000,1.000000,209.000000,3.000000,1991.000000,0.000000,0.000000,10.000000,0.000000,0.000000,15.000000,0.000000,8.000000,290.000000
25%,10280.75000,11.000000,1.000000,215.000000,25.000000,2012.000000,11.000000,16.000000,49.000000,16.000000,21.000000,21.000000,4.000000,21.000000,380.000000
50%,11560.50000,41.000000,5.000000,221.000000,27.000000,2016.000000,14.000000,20.000000,74.000000,19.000000,26.000000,24.000000,6.000000,126.000000,460.000000
75%,12336.25000,45.000000,9.000000,243.000000,29.000000,2020.000000,60.000000,41.000000,103.500000,26.000000,31.000000,31.000000,8.000000,254.750000,520.000000
max,13105.00000,57.000000,9.000000,470.000000,29.000000,2022.000000,800.000000,800.000000,142.000000,66.000000,231.000000,59.000000,12.000000,520.000000,640.000000

In [89]:
df5.shape

(3008, 29)

### Diccionario

1. **Vehicle ID:** Identificación del vehículo.
2. **Fuel ID:** Identificación del combustible.
3. **Fuel Configuration ID:** Identificación de la configuración del combustible.
4. **Manufacturer ID:** Identificación del fabricante.
5. **Category ID:** Identificación de la categoría.
6. **Model:** Modelo del vehículo.
7. **Model Year:** Año del modelo del vehículo.
8. **Alternative Fuel Economy City:** Economía de combustible alternativa en ciudad.
9. **Alternative Fuel Economy Highway:** Economía de combustible alternativa en carretera.
10. **Alternative Fuel Economy Combined:** Economía de combustible alternativa combinada.
11. **Conventional Fuel Economy City:** Economía de combustible convencional en ciudad.
12. **Conventional Fuel Economy Highway:** Economía de combustible convencional en carretera.
13. **Conventional Fuel Economy Combined:** Economía de combustible convencional combinada.
14. **Transmission Type:** Tipo de transmisión.
15. **Engine Type:** Tipo de motor.
16. **Engine Size:** Tamaño del motor.
17. **Engine Cylinder Count:** Cantidad de cilindros del motor.
18. **Engine Description:** Descripción del motor.
19. **Manufacturer:** Fabricante del vehículo.
20. **Manufacturer URL:** URL del fabricante.
21. **Category:** Categoría del vehículo.
22. **Fuel Code:** Código del combustible.
23. **Fuel:** Tipo de combustible.
24. **Fuel Configuration Name:** Nombre de la configuración del combustible.
25. **Electric-Only Range:** Rango solo eléctrico.
26. **PHEV Total Range:** Rango total de vehículos híbridos enchufables.
27. **PHEV Type:** Tipo de vehículo híbrido enchufable.
28. **Notes:** Notas adicionales.
29. **Drivetrain:** Tren motriz del vehículo.

Al analizar detenidamente nuestro conjunto de datos, hemos notado la presencia de algunas variables que ya habíamos eliminado anteriormente. Además, al observar la cantidad de valores nulos y revisar el diccionario de datos, hemos identificado que algunas de estas variables no serán significativas para nuestro objetivo actual.

Dado que trabajamos con un conjunto de datos anterior y deseamos mantener la coherencia, hemos decidido aplicar la misma lógica de eliminación de variables que empleamos en la iteración anterior. Esto implica descartar aquellas columnas que no aportan información relevante para nuestro análisis y que ya habíamos identificado previamente como prescindibles.

Este enfoque nos permite mantener la consistencia en nuestros datos y centrarnos en las variables que consideramos esenciales para cumplir con nuestros objetivos analíticos. A continuación, procederemos a realizar la eliminación de estas variables y a garantizar que nuestro conjunto de datos Light Duty Vehicles se alinee con nuestras necesidades de análisis actuales.

In [90]:
# Lista de variables a eliminar
variables_a_eliminar = ['PHEV Total Range', 'Engine Cylinder Count', 'Notes', 'Manufacturer URL', 'PHEV Type']

# Eliminar las variables del DataFrame
df5_filtered = df5.drop(variables_a_eliminar, axis=1)

In [91]:
df5_filtered.columns

Index(['Vehicle ID', 'Fuel ID', 'Fuel Configuration ID', 'Manufacturer ID',
       'Category ID', 'Model', 'Model Year', 'Alternative Fuel Economy City',
       'Alternative Fuel Economy Highway', 'Alternative Fuel Economy Combined',
       'Conventional Fuel Economy City', 'Conventional Fuel Economy Highway',
       'Conventional Fuel Economy Combined', 'Transmission Type',
       'Engine Type', 'Engine Size', 'Engine Description', 'Manufacturer',
       'Category', 'Fuel Code', 'Fuel', 'Fuel Configuration Name',
       'Electric-Only Range', 'Drivetrain'],
      dtype='object')

In [92]:
# revisamos los duplicados

num_duplicados = df5_filtered.duplicated().sum()

if num_duplicados > 0:
    print(f"Hay {num_duplicados} filas duplicadas en el DataFrame.")
else:
    print("No hay filas duplicadas en el DataFrame.")

No hay filas duplicadas en el DataFrame.

In [93]:
# Especifica el nombre del archivo
nombre_del_archivo = 'Light Duty Vehicles Cleaned.csv'

# Guarda el DataFrame en el archivo CSV
df5_filtered.to_csv('datasets/datasets_cleaned/' + nombre_del_archivo, index=False, encoding='utf-8')
print(f'Se ha guardado el archivo {nombre_del_archivo}', 'en la carpeta datasets_cleaned')

Se ha guardado el archivo Light Duty Vehicles Cleaned.csv en la carpeta datasets_cleaned

# Dataset 6: taxi+_zone_lookup

In [94]:
df6 = pd.read_csv('datasets/datasets_originales/taxi+_zone_lookup.csv')

In [95]:
df6.head(3)

   LocationID Borough                     Zone service_zone
0           1     EWR           Newark Airport          EWR
1           2  Queens              Jamaica Bay    Boro Zone
2           3   Bronx  Allerton/Pelham Gardens    Boro Zone

In [96]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       265 non-null    object
 2   Zone          264 non-null    object
 3   service_zone  263 non-null    object
dtypes: int64(1), object(3)
memory usage: 8.4+ KB

In [97]:
df6.isnull().sum()

LocationID      0
Borough         0
Zone            1
service_zone    2
dtype: int64

### diccionario

1. **LocationID:** Identificación de ubicación.
2. **Borough:** Distrito.
3. **Zone:** Zona geográfica.
4. **service_zone:** Zona de servicio.

Procedemos a examinar la presencia de valores nulos en las columnas LocationID, Borough, Zone y service_zone; visualizar los valores nulos y tomar decisiones sobre su manejo.

In [98]:
# Imprimir el número de valores nulos por columna
print("Valores nulos por columna:")
print(df6.isnull().sum())

# Visualizar filas con valores nulos
rows_with_nulls = df6[df6.isnull().any(axis=1)]
print("\nFilas con valores nulos:")
print(rows_with_nulls)

Valores nulos por columna:
LocationID      0
Borough         0
Zone            1
service_zone    2
dtype: int64

Filas con valores nulos:
     LocationID  Borough Zone service_zone
263         264  Unknown   NV          NaN
264         265  Unknown  NaN          NaN

hemos decidido eliminar las filas con valores nulos

In [99]:
# Eliminar filas con valores nulos y actualizar el DataFrame
df6 = df6.dropna()

# Verificar que no haya más valores nulos después de la eliminación
print("Valores nulos después de la eliminación:")
print(df6.isnull().sum())

Valores nulos después de la eliminación:
LocationID      0
Borough         0
Zone            0
service_zone    0
dtype: int64

In [100]:
# Especifica el nombre del archivo
nombre_del_archivo = 'taxi+_zone_lookup_Cleaned.csv'

# Guarda el DataFrame en el archivo CSV
df6.to_csv('datasets/datasets_cleaned/' + nombre_del_archivo, index=False, encoding='utf-8')
print(f'Se ha guardado el archivo {nombre_del_archivo}', 'en la carpeta datasets_cleaned')

Se ha guardado el archivo taxi+_zone_lookup_Cleaned.csv en la carpeta datasets_cleaned

# Dataset 7: Vehicle Fuel Economy Data

In [101]:
df7 = pd.read_csv('datasets/datasets_originales/Vehicle Fuel Economy Data.csv')

In [102]:
df7.head(3)

,Year,Manufacturer,Model,barrels08,barrelsA08,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,VClass,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,2017,BMW,M6 Coupe,17.500588,0.0,0.0,15.0,14.0,0.0,0.0,0.0,0.0,0.0,519.0,-1.0,0.0,519.0,17.0,17.0,0.0,0.0,0.0,0.0,0.0,8.0,4.4,Rear-Wheel Drive,660.0,SIDI,3.0,3850.0,0.0,Premium,Premium Gasoline,3.0,-1.0,22.0,21.0,0.0,0.0,Subcompact Cars,0.0,0.0,0.0,0.0,0.0,37330.0,13.0,0.0,N,False,87.0,0.0,0.0,0.0,0.0,0.0,0.0,Manual 6-spd,17.9989,0.0,30.0000,0.0,-9750.0,G,NaN,T,NaN,NaN,NaN,NaN,NaN,BMX,NaN,0.0,NaN,04-04-2016,09-09-2016,Y,0.0,0.0,0.0
1,2017,BMW,X3 sDrive28i,12.396250,0.0,0.0,21.0,21.0,0.0,0.0,0.0,0.0,0.0,374.0,-1.0,0.0,374.0,24.0,23.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,371.0,SIDI,5.0,2700.0,0.0,Premium,Premium Gasoline,5.0,-1.0,28.0,27.0,0.0,0.0,Small Sport Utility Vehicle 2WD,0.0,0.0,0.0,0.0,0.0,37343.0,0.0,0.0,N,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Automatic (S8),26.7866,0.0,39.2499,0.0,-4000.0,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,BMX,NaN,0.0,NaN,04-04-2016,22-11-2016,Y,0.0,0.0,0.0
2,2016,Infiniti,Q50S Red Sport,13.523182,0.0,0.0,20.0,19.0,0.0,0.0,0.0,0.0,0.0,402.0,-1.0,0.0,402.0,22.0,22.0,0.0,0.0,0.0,0.0,0.0,6.0,3.0,Rear-Wheel Drive,133.0,SIDI,5.0,2950.0,0.0,Premium,Premium Gasoline,5.0,-1.0,26.0,26.0,0.0,0.0,Midsize Cars,0.0,0.0,0.0,0.0,0.0,37348.0,0.0,14.0,N,False,0.0,100.0,0.0,0.0,0.0,0.0,0.0,Automatic (S7),25.1000,0.0,37.3000,0.0,-5250.0,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NSX,NaN,0.0,NaN,04-04-2016,26-09-2016,N,0.0,0.0,0.0

In [103]:
df7_2020 = df7[df7['Year'] >= 2020]

In [104]:
df7_2020.head(3)

,Year,Manufacturer,Model,barrels08,barrelsA08,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,VClass,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
872,2020,Toyota,Corolla,9.297187,0.0,0.0,29.0,28.0,0.0,0.0,0.0,0.0,0.0,277.0,-1.0,0.0,277.0,32.0,31.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,Front-Wheel Drive,11.0,SIDI & PFI,7.0,1650.0,0.0,Regular,Regular Gasoline,7.0,-1.0,36.0,36.0,0.0,0.0,Compact Cars,0.0,0.0,0.0,0.0,0.0,41215.0,0.0,13.0,N,False,0.0,89.0,0.0,0.0,0.0,0.0,0.0,Manual 6-spd,37.8991,0.0,53.3991,0.0,1250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TYX,NaN,0.0,NaN,06-02-2019,16-04-2019,N,0.0,0.0,0.0
873,2020,Kia,Soul Eco dynamics,9.597097,0.0,0.0,29.0,28.0,0.0,0.0,0.0,0.0,0.0,287.0,-1.0,0.0,287.0,31.0,31.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,Front-Wheel Drive,6.0,NaN,7.0,1700.0,0.0,Regular,Regular Gasoline,7.0,-1.0,35.0,35.0,0.0,0.0,Small Station Wagons,0.0,0.0,0.0,0.0,0.0,41221.0,0.0,24.0,Y,False,0.0,101.0,0.0,0.0,0.0,0.0,0.0,Automatic (variable gear ratios),37.9000,0.0,51.2000,0.0,1000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KMX,NaN,0.0,NaN,06-02-2019,16-04-2019,N,0.0,0.0,0.0
875,2020,Mercedes-Benz,GLE350 4matic,13.523182,0.0,0.0,19.0,19.0,0.0,0.0,0.0,0.0,0.0,404.0,-1.0,0.0,404.0,22.0,22.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,4-Wheel Drive,415.0,SIDI,4.0,2950.0,0.0,Premium,Premium Gasoline,4.0,-1.0,26.0,26.0,0.0,0.0,Small Sport Utility Vehicle 4WD,0.0,0.0,0.0,0.0,0.0,41233.0,0.0,0.0,Y,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Automatic 9-spd,24.5000,0.0,37.3000,0.0,-5250.0,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,MBX,NaN,0.0,NaN,12-02-2019,07-01-2020,Y,0.0,0.0,0.0

In [105]:
df7_2020.tail(3)

,Year,Manufacturer,Model,barrels08,barrelsA08,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,VClass,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
44947,2023,Hyundai,Ioniq 6 Long range AWD (18 inch Wheels),0.0672,0.0,7.0,130.0,130.0,0.0,0.0,0.0,26.0,0.0,0.0,-1.0,0.0,0.0,121.0,121.0,0.0,0.0,28.0,0.0,0.0,NaN,NaN,All-Wheel Drive,62.0,NaN,10.0,600.0,0.0,Electricity,Electricity,10.0,-1.0,111.0,111.0,0.0,0.0,Midsize Cars,0.0,29.0,0.0,0.0,0.0,46620.0,0.0,11.0,NaN,False,0.0,105.0,316.0,0.0,0.0,0.0,0.0,Automatic (A1),190.5,0.0,162.6,0.0,6500.0,NaN,NaN,NaN,NaN,EV,NaN,NaN,74 and 165 kW PMSM,HYX,NaN,0.0,NaN,17-05-2023,17-05-2023,N,0.0,0.0,0.0
44948,2023,Hyundai,Ioniq 6 Long range RWD (18 inch Wheels),0.0576,0.0,7.0,153.0,153.0,0.0,0.0,0.0,21.0,0.0,0.0,-1.0,0.0,0.0,140.0,140.0,0.0,0.0,23.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,60.0,NaN,10.0,500.0,0.0,Electricity,Electricity,10.0,-1.0,127.0,127.0,0.0,0.0,Midsize Cars,0.0,27.0,0.0,0.0,0.0,46622.0,0.0,11.0,NaN,False,0.0,105.0,361.0,0.0,0.0,0.0,0.0,Automatic (A1),208.6,0.0,173.9,0.0,7000.0,NaN,NaN,NaN,NaN,EV,NaN,NaN,168 kW PMSM,HYX,NaN,0.0,NaN,17-05-2023,17-05-2023,N,0.0,0.0,0.0
44949,2023,Hyundai,Ioniq 6 Long range RWD (20 inch Wheels),0.0696,0.0,7.0,129.0,129.0,0.0,0.0,0.0,26.0,0.0,0.0,-1.0,0.0,0.0,117.0,117.0,0.0,0.0,29.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,61.0,NaN,10.0,600.0,0.0,Electricity,Electricity,10.0,-1.0,105.0,105.0,0.0,0.0,Midsize Cars,0.0,32.0,0.0,0.0,0.0,46623.0,0.0,11.0,NaN,False,0.0,105.0,305.0,0.0,0.0,0.0,0.0,Automatic (A1),178.6,0.0,145.0,0.0,6500.0,NaN,NaN,NaN,NaN,EV,NaN,NaN,168 kW PMSM,HYX,NaN,0.0,NaN,17-05-2023,17-05-2023,N,0.0,0.0,0.0

In [106]:
df7_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5247 entries, 872 to 44949
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             5247 non-null   int64
 1   Manufacturer     5247 non-null   object
 2   Model            5247 non-null   object
 3   barrels08        5242 non-null   float64
 4   barrelsA08       5242 non-null   float64
 5   charge240        5242 non-null   float64
 6   city08           5242 non-null   float64
 7   city08U          5242 non-null   float64
 8   cityA08          5242 non-null   float64
 9   cityA08U         5242 non-null   float64
 10  cityCD           5242 non-null   float64
 11  cityE            5242 non-null   float64
 12  cityUF           5242 non-null   float64
 13  co2              5242 non-null   float64
 14  co2A             5242 non-null   float64
 15  co2TailpipeAGpm  5242 non-null   float64
 16  co2TailpipeGpm   5242 non-null   float64
 17  comb08           5242 non-null   float64
 18  comb08U          5242 non-null   float64
 19  combA08          5242 non-null   float64
 20  combA08U         5242 non-null   float64
 21  combE            5242 non-null   float64
 22  combinedCD       5242 non-null   float64
 23  combinedUF       5242 non-null   float64
 24  cylinders        4942 non-null   float64
 25  displ            4942 non-null   float64
 26  drive            5242 non-null   object
 27  engId            5242 non-null   float64
 28  eng_dscr         4257 non-null   object
 29  feScore          5242 non-null   float64
 30  fuelCost08       5242 non-null   float64
 31  fuelCostA08      5242 non-null   float64
 32  fuelType         5242 non-null   object
 33  fuelType1        5242 non-null   object
 34  ghgScore         5242 non-null   float64
 35  ghgScoreA        5242 non-null   float64
 36  highway08        5242 non-null   float64
 37  highway08U       5242 non-null   float64
 38  highwayA08       5242 non-null   float64
 39  highwayA08U      5242 non-null   float64
 40  VClass           5242 non-null   object
 41  highwayCD        5236 non-null   float64
 42  highwayE         5236 non-null   float64
 43  highwayUF        5236 non-null   float64
 44  hlv              5236 non-null   float64
 45  hpv              5236 non-null   float64
 46  id               5236 non-null   float64
 47  lv2              5236 non-null   float64
 48  lv4              5236 non-null   float64
 49  mpgData          5223 non-null   object
 50  phevBlended      5236 non-null   object
 51  pv2              5236 non-null   float64
 52  pv4              5236 non-null   float64
 53  range            5236 non-null   float64
 54  rangeCity        5236 non-null   float64
 55  rangeCityA       5236 non-null   float64
 56  rangeHwy         5236 non-null   float64
 57  rangeHwyA        5236 non-null   float64
 58  trany            5236 non-null   object
 59  UCity            5236 non-null   float64
 60  UCityA           5236 non-null   float64
 61  UHighway         5236 non-null   float64
 62  UHighwayA        5236 non-null   float64
 63  youSaveSpend     5236 non-null   float64
 64  guzzler          284 non-null    object
 65  trans_dscr       0 non-null      object
 66  tCharger         2921 non-null   object
 67  sCharger         167 non-null    object
 68  atvType          1186 non-null   object
 69  fuelType2        225 non-null    object
 70  rangeA           225 non-null    object
 71  evMotor          1019 non-null   object
 72  mfrCode          5216 non-null   object
 73  c240Dscr         51 non-null     object
 74  charge240b       5216 non-null   float64
 75  c240bDscr        49 non-null     object
 76  createdOn        5216 non-null   object
 77  modifiedOn       5216 non-null   object
 78  startStop        5216 non-null   object
 79  phevCity         5216 non-null   float64
 80  phevHwy          5216 non-null   float64
 81  phevComb         5216 non-null   float64
dtypes: float64(57), int64(1), object(24)
memory usage: 3.3+ MB

In [107]:
df7_2020.describe()

,Year,barrels08,barrelsA08,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,engId,feScore,fuelCost08,fuelCostA08,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,UCity,UCityA,UHighway,UHighwayA,youSaveSpend,charge240b,phevCity,phevHwy,phevComb
count,5247.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.0,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.00000,5242.000000,5242.000000,5242.0,5242.0,4942.000000,4942.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.000000,5242.00000,5242.000000,5236.0,5236.000000,5236.0,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5236.000000,5216.000000,5216.000000,5216.000000,5216.000000
mean,2021.569849,12.782979,0.175506,0.663106,25.554369,25.127432,2.201831,2.198588,0.000191,3.606066,0.0,380.621709,5.438573,6.424838,380.621709,27.485883,27.055895,2.20145,2.192675,3.662152,0.0,0.0,5.597329,3.116734,269.403663,4.922549,2647.977871,46.308661,4.950973,-0.936093,30.879054,30.463373,2.22625,2.223960,0.0,3.731856,0.0,1.417685,6.506494,43969.340718,1.251719,4.718105,10.461039,28.385409,15.385409,8.553667,0.804431,7.768144,0.760504,33.526944,3.082506,44.141600,1.861536,-3640.040107,0.051764,1.189034,1.211465,1.194018
std,1.165830,4.735184,0.884531,2.419513,20.655999,20.698713,12.343896,12.349752,0.013812,12.482979,0.0,141.020489,55.000353,54.884877,141.020489,18.958160,18.988567,12.05463,12.039728,12.502903,0.0,0.0,1.890157,1.326986,271.598037,2.005933,920.291464,369.040400,2.066736,0.551072,17.015685,17.044279,11.87483,11.880913,0.0,12.569224,0.0,5.354332,23.558040,1545.908745,3.506093,8.214204,27.575674,45.182242,64.638583,50.296838,5.757794,46.054613,5.217626,29.535862,17.565434,23.709034,12.729532,4642.701867,0.630333,7.522515,7.331616,7.390332
min,2020.000000,0.057600,0.000000,0.000000,8.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,-1.000000,0.000000,0.000000,9.000000,9.000000,0.00000,0.000000,0.000000,0.0,0.0,2.000000,0.600000,1.000000,1.000000,500.000000,0.000000,1.000000,-1.000000,11.000000,11.000000,0.00000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,41213.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.300000,0.000000,15.100000,0.000000,-26750.000000,0.000000,0.000000,0.000000,0.000000
25%,2021.000000,10.625357,0.000000,0.000000,17.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.0,321.000000,-1.000000,0.000000,321.000000,19.000000,19.000000,0.00000,0.000000,0.000000,0.0,0.0,4.000000,2.000000,43.000000,4.000000,2100.000000,0.000000,4.000000,-1.000000,23.000000,22.000000,0.00000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,42630.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.984800,0.000000,32.400000,0.000000,-6750.000000,0.000000,0.000000,0.000000,0.000000
50%,2022.000000,12.935217,0.000000,0.000000,20.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.0,390.000000,-1.000000,0.000000,390.000000,23.000000,22.000000,0.00000,0.000000,0.000000,0.0,0.0,6.000000,3.000000,138.000000,5.000000,2600.000000,0.000000,5.000000,-1.000000,27.000000,26.000000,0.00000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,43985.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,25.633200,0.000000,38.403800,0.000000,-3500.000000,0.000000,0.000000,0.000000,0.000000
75%,2023.000000,15.658421,0.000000,0.000000,24.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.0,466.000000,-1.000000,0.000000,466.000000,27.000000,27.000000,0.00000,0.000000,0.000000,0.0,0.0,6.000000,3.600000,505.000000,6.000000,3250.000000,0.000000,6.000000,-1.000000,32.000000,31.000000,0.00000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,45312.250000,0.000000,11.000000,0.000000,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,31.407400,0.000000,46.037975,0.000000,-750.000000,0.000000,0.000000,0.000000,0.000000
max,2024.000000,33.056667,7.000000,19.000000,153.000000,153.000000,145.000000,145.000000,1.000000,90.000000,0.0,979.000000,571.000000,571.000000,979.000000,142.000000,141.000000,133.00000,133.000000,86.000000,0.0,0.0,16.000000,8.000000,999.000000,10.000000,7250.000000,3800.000000,10.000000,6.000000,140.000000,140.000000,121.00000,121.000000,0.0,82.000000,0.0,27.000000,101.000000,46624.000000,22.000000,47.000000,118.000000,157.000000,520.000000,520.000000,135.000000,520.000000,114.000000,221.500000,207.000000,187.100000,173.000000,7000.000000,9.000000,92.000000,79.000000,86.000000

In [108]:
pd.set_option('display.max_rows', None)

In [109]:
df7_2020.isnull().sum()

Year                  0
Manufacturer          0
Model                 0
barrels08             5
barrelsA08            5
charge240             5
city08                5
city08U               5
cityA08               5
cityA08U              5
cityCD                5
cityE                 5
cityUF                5
co2                   5
co2A                  5
co2TailpipeAGpm       5
co2TailpipeGpm        5
comb08                5
comb08U               5
combA08               5
combA08U              5
combE                 5
combinedCD            5
combinedUF            5
cylinders           305
displ               305
drive                 5
engId                 5
eng_dscr            990
feScore               5
fuelCost08            5
fuelCostA08           5
fuelType              5
fuelType1             5
ghgScore              5
ghgScoreA             5
highway08             5
highway08U            5
highwayA08            5
highwayA08U           5
VClass                5
highwayCD            11
highwayE             11
highwayUF            11
hlv                  11
hpv                  11
id                   11
lv2                  11
lv4                  11
mpgData              24
phevBlended          11
pv2                  11
pv4                  11
range                11
rangeCity            11
rangeCityA           11
rangeHwy             11
rangeHwyA            11
trany                11
UCity                11
UCityA               11
UHighway             11
UHighwayA            11
youSaveSpend         11
guzzler            4963
trans_dscr         5247
tCharger           2326
sCharger           5080
atvType            4061
fuelType2          5022
rangeA             5022
evMotor            4228
mfrCode              31
c240Dscr           5196
charge240b           31
c240bDscr          5198
createdOn            31
modifiedOn           31
startStop            31
phevCity             31
phevHwy              31
phevComb             31
dtype: int64

In [110]:
df7_2020.shape

(5247, 82)

### Diccionario

1. **Year:** Año del vehículo.
2. **Manufacturer:** Fabricante del vehículo.
3. **Model:** Modelo del vehículo.
4. **barrels08:** Consumo de barriles por cada 100 millas en ciudad.
5. **barrelsA08:** Consumo de barriles alternativo por cada 100 millas en ciudad.
6. **charge240:** Tiempo de carga a 240V.
7. **city08:** Consumo de gasolina en ciudad por cada 100 millas.
8. **city08U:** Consumo de gasolina en ciudad por cada 100 millas ajustado.
9. **cityA08:** Consumo alternativo en ciudad por cada 100 millas.
10. **cityA08U:** Consumo alternativo en ciudad por cada 100 millas ajustado.
11. **cityCD:** Consumo de gasolina en ciudad por cada 100 millas (diesel).
12. **cityE:** Consumo de electricidad en ciudad.
13. **cityUF:** Consumo de gasolina en ciudad ajustado (fuel economy).
14. **co2:** Emisiones de CO2 en gramos por milla.
15. **co2A:** Emisiones alternativas de CO2 en gramos por milla.
16. **co2TailpipeAGpm:** Emisiones de CO2 de la tubería de escape alternativa en gramos por milla.
17. **co2TailpipeGpm:** Emisiones de CO2 de la tubería de escape en gramos por milla.
18. **comb08:** Consumo de gasolina combinado por cada 100 millas.
19. **comb08U:** Consumo de gasolina combinado por cada 100 millas ajustado.
20. **combA08:** Consumo alternativo combinado por cada 100 millas.
21. **combA08U:** Consumo alternativo combinado por cada 100 millas ajustado.
22. **combE:** Consumo de electricidad combinado.
23. **combinedCD:** Consumo de gasolina combinado por cada 100 millas (diesel).
24. **combinedUF:** Consumo de gasolina combinado ajustado (fuel economy).
25. **cylinders:** Número de cilindros.
26. **displ:** Desplazamiento del motor en litros.
27. **drive:** Tipo de tracción del vehículo.
28. **engId:** Identificación del motor.
29. **eng_dscr:** Descripción del motor.
30. **feScore:** Puntuación de eficiencia de combustible.
31. **fuelCost08:** Costo de combustible en dólares por año (fuel economy).
32. **fuelCostA08:** Costo de combustible alternativo en dólares por año (fuel economy).
33. **fuelType:** Tipo de combustible del vehículo.
34. **fuelType1:** Tipo de combustible primario.
35. **ghgScore:** Puntuación de emisiones de gases de efecto invernadero.
36. **ghgScoreA:** Puntuación alternativa de emisiones de gases de efecto invernadero.
37. **highway08:** Consumo de gasolina en carretera por cada 100 millas.
38. **highway08U:** Consumo de gasolina en carretera por cada 100 millas ajustado.
39. **highwayA08:** Consumo alternativo en carretera por cada 100 millas.
40. **highwayA08U:** Consumo alternativo en carretera por cada 100 millas ajustado.
41. **VClass:** Clase de vehículo.
42. **highwayCD:** Consumo de gasolina en carretera por cada 100 millas (diesel).
43. **highwayE:** Consumo de electricidad en carretera.
44. **highwayUF:** Consumo de gasolina en carretera ajustado (fuel economy).
45. **hlv:** Volumen de carga útil.
46. **hpv:** Potencia neta del vehículo.
47. **id:** Identificación del vehículo.
48. **lv2:** Volumen de carga útil a nivel 2.
49. **lv4:** Volumen de carga útil a nivel 4.
50. **mpgData:** Información de consumo de combustible.
51. **phevBlended:** Indica si el vehículo es híbrido enchufable.
52. **pv2:** Potencia neta del vehículo a nivel 2.
53. **pv4:** Potencia neta del vehículo a nivel 4.
54. **range:** Rango del vehículo.
55. **rangeCity:** Rango en ciudad del vehículo.
56. **rangeCityA:** Rango en ciudad alternativo del vehículo.
57. **rangeHwy:** Rango en carretera del vehículo.
58. **rangeHwyA:** Rango en carretera alternativo del vehículo.
59. **trany:** Tipo de transmisión.
60. **UCity:** Consumo de gasolina ajustado en ciudad.
61. **UCityA:** Consumo de gasolina ajustado en ciudad alternativo.
62. **UHighway:** Consumo de gasolina ajustado en carretera.
63. **UHighwayA:** Consumo de gasolina ajustado en carretera alternativo.
64. **youSaveSpend:** Ahorro o gasto estimado en combustible durante 5 años.
65. **guzzler:** Indica si el vehículo es un derrochador de combustible.
66. **trans_dscr:** Descripción de la transmisión.
67. **tCharger:** Indica si el vehículo tiene un cargador térmico.
68. **sCharger:** Indica si el vehículo tiene un cargador solar.
69. **atvType:** Tipo de vehículo todo terreno.
70. **fuelType2:** Segundo tipo de combustible del vehículo.
71. **rangeA:** Rango alternativo del vehículo.
72. **evMotor:** Tipo de motor eléctrico.
73. **mfrCode:** Código del fabricante.
74. **c240Dscr:** Descripción del cargador a 240V.
75. **charge240b:** Tiempo de carga a